import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';

class ReportGenerator {
  Future<Uint8List> generateReport(
      String studentName, List<Map<String, dynamic>> examResults) async {
    final pdf = pw.Document();

    // Load a font (Standard Helvetica is built-in, but this helps ensures support)
    // For Sinhala support, you'd need to load a custom .ttf font here.
    // For now, we will stick to English for the Report Card to keep it simple.

    // Calculate Averages
    int totalScore = 0;
    int totalQuestions = 0;
    for (var result in examResults) {
      totalScore += (result['score'] as int);
      totalQuestions += (result['total'] as int);
    }
    double average = totalQuestions == 0 ? 0 : (totalScore / totalQuestions) * 100;
    String grade = _calculateGrade(average);

    // Create the PDF Page
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // HEADER
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("SisuPal Progress Report",
                        style: pw.TextStyle(
                            fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue)),
                    pw.Text(DateFormat('yyyy-MM-dd').format(DateTime.now())),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // STUDENT INFO
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey),
                  borderRadius: pw.BorderRadius.circular(5),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text("Student Name: $studentName",
                        style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                    pw.Text("Generated By: Parent Dashboard"),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),

              // SCORE TABLE
              pw.Table.fromTextArray(
                context: context,
                border: null,
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.blue),
                rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey, width: 0.5))),
                cellPadding: const pw.EdgeInsets.all(8),
                headers: ['Date', 'Subject', 'Score', 'Total', 'Percentage'],
                data: examResults.map((result) {
                  final date = (result['date'] as DateTime?) ?? DateTime.now();
                  final dateStr = DateFormat('MM/dd/yyyy').format(date);
                  final score = result['score'];
                  final total = result['total'];
                  final percent = ((score / total) * 100).toStringAsFixed(1) + "%";

                  return [dateStr, result['examTitle'], score.toString(), total.toString(), percent];
                }).toList(),
              ),

              pw.SizedBox(height: 20),
              pw.Divider(),

              // SUMMARY
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text("Overall Average: ${average.toStringAsFixed(1)}%",
                          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      pw.Text("Overall Grade: $grade",
                          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.green)),
                    ],
                  ),
                ],
              ),

              pw.Spacer(),

              // FOOTER
              pw.Center(
                child: pw.Text("Keep up the good work! - Team SisuPal",
                    style: const pw.TextStyle(color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  String _calculateGrade(double avg) {
    if (avg >= 75) return "A (Excellent)";
    if (avg >= 65) return "B (Very Good)";
    if (avg >= 50) return "C (Good)";
    if (avg >= 35) return "S (Pass)";
    return "W (Needs Improvement)";
  }
}