import { initializeApp } from "firebase/app";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import { getFirestore, doc, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyAHn3e3YIOH-TvQOL6HF-JTvwXXH97tBS4",
  authDomain: "sisupal-782d3.firebaseapp.com",
  projectId: "sisupal-782d3",
  storageBucket: "sisupal-782d3.firebasestorage.app",
  messagingSenderId: "213942877787",
  appId: "1:213942877787:web:814aadc8f8fd5e523a497e",
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

const MOCK_STUDENTS = [
  {
    id: "student_kasun_01",
    name: "කසුන් පෙරේරා (Kasun Perera)",
    grade: 5,
    district: "Colombo",
    xp: 1450,
    streak: 7,
    role: "student",
    isStudent: true,
    lastActiveDate: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Kasun",
    email: "kasun.p@sisupal.lk",
    school: "Royal College, Colombo",
    totalQuestionsAttempted: 20,
    overallAccuracy: 80,
    questionAttempts: [
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), questionId: "q_p1", conceptId: "c1_jungle_map" },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date(Date.now() - 1000 * 60 * 28).toISOString(), questionId: "q_p2", conceptId: "c1_jungle_map" },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(), questionId: "q_p3", conceptId: "c1_jungle_map" },
      { skillTag: "place_value_identification", isCorrect: false, hintUsed: true, timeTaken: 22, timestamp: new Date(Date.now() - 1000 * 60 * 22).toISOString(), questionId: "q_p4", conceptId: "c1_jungle_map" },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(), questionId: "q_p5", conceptId: "c1_jungle_map" },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(), questionId: "q_p6", conceptId: "c1_jungle_map" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date(Date.now() - 1000 * 60 * 16).toISOString(), questionId: "q_c1", conceptId: "c1_number_train_station" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 15, timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(), questionId: "q_c2", conceptId: "c1_number_train_station" },
      { skillTag: "place_value_comparison", isCorrect: false, hintUsed: true, timeTaken: 25, timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(), questionId: "q_c3", conceptId: "c1_number_train_station" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(), questionId: "q_c4", conceptId: "c1_number_train_station" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(), questionId: "q_c5", conceptId: "c1_number_train_station" },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 30, timestamp: new Date(Date.now() - 1000 * 60 * 6).toISOString(), questionId: "q_e1", conceptId: "c5_unlocking_chest" },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 18, timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), questionId: "q_e2", conceptId: "c5_unlocking_chest" },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 28, timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(), questionId: "q_e3", conceptId: "c5_unlocking_chest" },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 35, timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(), questionId: "q_e4", conceptId: "c5_unlocking_chest" },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 16, timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(), questionId: "q_e5", conceptId: "c5_unlocking_chest" },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(), questionId: "q_o1", conceptId: "c2_number_train_ordering" },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date(Date.now() - 1000 * 60 * 1).toISOString(), questionId: "q_o2", conceptId: "c2_number_train_ordering" },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: false, timeTaken: 19, timestamp: new Date(Date.now() - 1000 * 45).toISOString(), questionId: "q_o3", conceptId: "c2_number_train_ordering" },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date(Date.now() - 1000 * 20).toISOString(), questionId: "q_o4", conceptId: "c2_number_train_ordering" },
    ],
  },
  {
    id: "student_dinithi_02",
    name: "දිනිති සිල්වා (Dinithi Silva)",
    grade: 5,
    district: "Gampaha",
    xp: 2120,
    streak: 14,
    role: "student",
    isStudent: true,
    lastActiveDate: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Dinithi",
    email: "dinithi.s@sisupal.lk",
    school: "Holy Cross College, Gampaha",
    totalQuestionsAttempted: 20,
    overallAccuracy: 95,
    questionAttempts: [
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 6, timestamp: new Date().toISOString(), questionId: "q_d1" },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 7, timestamp: new Date().toISOString(), questionId: "q_d2" },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 5, timestamp: new Date().toISOString(), questionId: "q_d3" },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date().toISOString(), questionId: "q_d4" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date().toISOString(), questionId: "q_d5" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 7, timestamp: new Date().toISOString(), questionId: "q_d6" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString(), questionId: "q_d7" },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date().toISOString(), questionId: "q_d8" },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date().toISOString(), questionId: "q_d9" },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString(), questionId: "q_d10" },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date().toISOString(), questionId: "q_d11" },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 20, timestamp: new Date().toISOString(), questionId: "q_d12" },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date().toISOString(), questionId: "q_d13" },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date().toISOString(), questionId: "q_d14" },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString(), questionId: "q_d15" },
      { skillTag: "digit_builder", isCorrect: true, hintUsed: false, timeTaken: 13, timestamp: new Date().toISOString(), questionId: "q_d16" },
      { skillTag: "digit_builder", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString(), questionId: "q_d17" },
      { skillTag: "large_numbers_reading", isCorrect: true, hintUsed: false, timeTaken: 7, timestamp: new Date().toISOString(), questionId: "q_d18" },
      { skillTag: "large_numbers_reading", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date().toISOString(), questionId: "q_d19" },
      { skillTag: "large_numbers_reading", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date().toISOString(), questionId: "q_d20" },
    ],
  },
  {
    id: "student_thinura_03",
    name: "තිනුර ජයවර්ධන (Thinura Jayawardena)",
    grade: 5,
    district: "Kandy",
    xp: 890,
    streak: 3,
    role: "student",
    isStudent: true,
    lastActiveDate: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Thinura",
    email: "thinura.j@sisupal.lk",
    school: "Kingswood College, Kandy",
    totalQuestionsAttempted: 20,
    overallAccuracy: 60,
    questionAttempts: [
      { skillTag: "abacus_representation", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString() },
      { skillTag: "abacus_representation", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date().toISOString() },
      { skillTag: "abacus_representation", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date().toISOString() },
      { skillTag: "abacus_representation", isCorrect: false, hintUsed: false, timeTaken: 15, timestamp: new Date().toISOString() },
      { skillTag: "abacus_representation", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: true, timeTaken: 25, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: true, timeTaken: 30, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 16, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: true, timeTaken: 28, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: true, timeTaken: 32, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 18, timestamp: new Date().toISOString() },
      { skillTag: "large_numbers_reading", isCorrect: false, hintUsed: true, timeTaken: 22, timestamp: new Date().toISOString() },
      { skillTag: "large_numbers_reading", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date().toISOString() },
      { skillTag: "large_numbers_reading", isCorrect: false, hintUsed: true, timeTaken: 26, timestamp: new Date().toISOString() },
      { skillTag: "large_numbers_reading", isCorrect: false, hintUsed: false, timeTaken: 19, timestamp: new Date().toISOString() },
      { skillTag: "large_numbers_reading", isCorrect: true, hintUsed: false, timeTaken: 15, timestamp: new Date().toISOString() },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date().toISOString() },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date().toISOString() },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString() },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 7, timestamp: new Date().toISOString() },
    ],
  },
  {
    id: "student_oshadhi_04",
    name: "ඕෂදී ප්‍රනාන්දු (Oshadhi Fernando)",
    grade: 5,
    district: "Galle",
    xp: 1780,
    streak: 9,
    role: "student",
    isStudent: true,
    lastActiveDate: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Oshadhi",
    email: "oshadhi.f@sisupal.lk",
    school: "Southlands College, Galle",
    totalQuestionsAttempted: 20,
    overallAccuracy: 75,
    questionAttempts: [
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString() },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date().toISOString() },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString() },
      { skillTag: "place_value_comparison", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date().toISOString() },
      { skillTag: "digit_builder", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date().toISOString() },
      { skillTag: "digit_builder", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date().toISOString() },
      { skillTag: "digit_builder", isCorrect: true, hintUsed: false, timeTaken: 15, timestamp: new Date().toISOString() },
      { skillTag: "digit_builder", isCorrect: false, hintUsed: true, timeTaken: 22, timestamp: new Date().toISOString() },
      { skillTag: "digit_builder", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString() },
      { skillTag: "place_value_word_form", isCorrect: false, hintUsed: true, timeTaken: 25, timestamp: new Date().toISOString() },
      { skillTag: "place_value_word_form", isCorrect: true, hintUsed: false, timeTaken: 13, timestamp: new Date().toISOString() },
      { skillTag: "place_value_word_form", isCorrect: false, hintUsed: true, timeTaken: 28, timestamp: new Date().toISOString() },
      { skillTag: "place_value_word_form", isCorrect: false, hintUsed: false, timeTaken: 18, timestamp: new Date().toISOString() },
      { skillTag: "place_value_word_form", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 24, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 26, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString() },
    ],
  },
  {
    id: "student_kaveen_05",
    name: "කවීන් වික්‍රමසිංහ (Kaveen Wickramasinghe)",
    grade: 5,
    district: "Jaffna",
    xp: 1220,
    streak: 5,
    role: "student",
    isStudent: true,
    lastActiveDate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Kaveen",
    email: "kaveen.w@sisupal.lk",
    school: "St. John's College, Jaffna",
    totalQuestionsAttempted: 20,
    overallAccuracy: 70,
    questionAttempts: [
      { skillTag: "train_concept", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString() },
      { skillTag: "train_concept", isCorrect: true, hintUsed: false, timeTaken: 9, timestamp: new Date().toISOString() },
      { skillTag: "train_concept", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date().toISOString() },
      { skillTag: "train_concept", isCorrect: true, hintUsed: false, timeTaken: 8, timestamp: new Date().toISOString() },
      { skillTag: "train_concept", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString() },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString() },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date().toISOString() },
      { skillTag: "place_value_identification", isCorrect: false, hintUsed: false, timeTaken: 16, timestamp: new Date().toISOString() },
      { skillTag: "place_value_identification", isCorrect: true, hintUsed: false, timeTaken: 11, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 15, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 25, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: false, hintUsed: true, timeTaken: 28, timestamp: new Date().toISOString() },
      { skillTag: "expanded_form", isCorrect: true, hintUsed: false, timeTaken: 13, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: true, timeTaken: 22, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 14, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: true, timeTaken: 24, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 12, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: false, hintUsed: false, timeTaken: 18, timestamp: new Date().toISOString() },
      { skillTag: "number_ordering", isCorrect: true, hintUsed: false, timeTaken: 10, timestamp: new Date().toISOString() },
    ],
  },
];

async function seed() {
  await signInWithEmailAndPassword(auth, "testadmin@gmail.com", "Admin123@");
  console.log("Logged in!");

  for (const s of MOCK_STUDENTS) {
    const { id, ...data } = s;
    await setDoc(doc(db, "users", id), data);
    console.log(`✅ Seeded student: ${s.name} (${s.district})`);
  }

  console.log("All 5 mock students seeded successfully!");
  process.exit(0);
}

seed().catch(console.error);
