org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djava.net.preferIPv4Stack=true -Djavax.net.ssl.trustStoreType=JKS
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false

# Hotspot and mobile network timeout & keep-alive fixes
systemProp.http.keepAlive=false
systemProp.https.keepAlive=false
systemProp.http.connectionTimeout=180000
systemProp.http.socketTimeout=180000
systemProp.https.connectionTimeout=180000
systemProp.https.socketTimeout=180000