import { StoryQuest } from "@/types";

export const OFFICIAL_STORY_QUESTS: StoryQuest[] = [
  // ─── LESSON 1: THE GOLDEN MANGO QUEST (5 CONCEPTS) ─────────────────────────
  {
    id: "quest_c1_jungle_map",
    title: "පාඩම 1 - සංකල්පය 1: අංක කැලෑ සිතියම (The Jungle Map)",
    conceptId: "c1_jungle_map",
    chapterNumber: 1,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "c1_beat_1",
        speaker: "Leo",
        dialogueText: "මෙන්න බලන්න පැරණි සිතියමක්! රන් අඹ ගෙඩිය සොයායන පාර හොයාගන්න නම් 84, 101, 528 සහ 997 කියන අංක ඇති ගස් පසුකරගෙන යන්න ඕනේ!",
        hasInteractiveGate: false,
      },
      {
        id: "c1_beat_2",
        speaker: "Felix",
        dialogueText: "අපෝ... අංක කියවන්න මහන්සි වෙන්නේ ඇයි? ඇස් දෙක පියාගෙන කොළ තියෙන ඕනෑම ගහක් ළඟින් දුවමු!",
        hasInteractiveGate: false,
      },
      {
        id: "c1_beat_3",
        speaker: "Ella",
        dialogueText: "අනේ ෆීලික්ස්, එහෙම කළොත් අපි මුළු කැලේම අතරමං වෙයි! 9,999 දක්වා සංඛ්‍යා නිවැරදිව කියවන්න සහ ලියන්න අපි දැනගන්න ඕනේ.",
        hasInteractiveGate: false,
      },
      {
        id: "c1_beat_4",
        speaker: "Ella",
        dialogueText: "යහළුවේ, නිවැරදි පාර තෝරාගන්න අපිට මේ අංක ටික කියවන්න උදව් කරනවද?",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c2_river_of_beads",
    title: "පාඩම 1 - සංකල්පය 2: පබළු ගඟ (The River of Beads)",
    conceptId: "c2_river_of_beads",
    chapterNumber: 2,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "c2_beat_1",
        speaker: "Leo",
        dialogueText: "අනේ පාලම කැඩිලා! ඒත් බලන්න, මෙතන ඒකස්ථානය, දහස්ථානය, සියස්ථානය, සහ දහස්ස්ථානය කියලා කණු 4ක් තියෙනවා. අපි මේ ගල් කැට තියන්නේ කොහොමද?",
        hasInteractiveGate: false,
      },
      {
        id: "c2_beat_2",
        speaker: "Felix",
        dialogueText: "ඒක හරිම ලේසියි! හැම ගල් කැටයක්ම පළමු කණුවට දාමු! ගල් කැටයක් කියන්නේ ගල් කැටයක්නේ, කොතැන තිබ්බම මොකද?",
        hasInteractiveGate: false,
      },
      {
        id: "c2_beat_3",
        speaker: "Ella",
        dialogueText: "ෆීලික්ස්, ස්ථානීය අගය ක්‍රියා කරන්නේ එහෙම නෙවෙයි! ගල් කැටයක් දහස්ස්ථානයට දැම්මම ඒකෙන් එකස්ථානයට වඩා ගොඩක් විශාල අගයක් නිරූපණය වෙනවා.",
        hasInteractiveGate: false,
      },
      {
        id: "c2_beat_4",
        speaker: "Ella",
        dialogueText: "යහළුවේ, පාලම නැවත හදන්න මේ ගල් කැට නිවැරදි කණුවල තියන්න අපිට උදව් කරනවද?",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c3_giants_gate",
    title: "පාඩම 1 - සංකල්පය 3: යෝධයාගේ දොරටුව (The Giant's Gate)",
    conceptId: "c3_giants_gate",
    chapterNumber: 3,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "c3_beat_1",
        speaker: "Leo",
        dialogueText: "අම්මෝ, මේ දොරටුව කොච්චර විශාලද! දොරටුව අරින්න නම් 10,100 හෝ 25,602 වගේ මහා සංඛ්‍යාවක රහස් පදය කියන්න ඕනේ. මම මෙච්චර ලොකු අංක ගැන අහලා නෑ!",
        hasInteractiveGate: false,
      },
      {
        id: "c3_beat_2",
        speaker: "Felix",
        dialogueText: "හයියෙන් \"දහයයි!\" කියලා කෑගහමු! දොරටු ගොඩක් කැමතියි දහය කියන අංකයට. ඔය ඉතිරි ඉලක්කම් ගැන හිතන්න ඕනේ නෑ!",
        hasInteractiveGate: false,
      },
      {
        id: "c3_beat_3",
        speaker: "Ella",
        dialogueText: "ඒක හරියන්නේ නෑ ෆීලික්ස්! මේවා සියක් දහස (100,000) දක්වා ඇති විශාල සංඛ්‍යා. දොරටුව අරින්න නම් අපි ඒවා නිවැරදිව කියවන්න ඕනේ.",
        hasInteractiveGate: false,
      },
      {
        id: "c3_beat_4",
        speaker: "Ella",
        dialogueText: "යහළුවේ, නිවැරදි විශාල සංඛ්‍යාව හඳුනාගන්න අපිට උදව් කරනවද?",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c4_glowing_pedestals",
    title: "පාඩම 1 - සංකල්පය 4: දිදුලන වේදිකා (The Glowing Pedestals)",
    conceptId: "c4_glowing_pedestals",
    chapterNumber: 4,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "c4_beat_1",
        speaker: "Leo",
        dialogueText: "රහස් අංකය 68,507! ඒත් කෝකටද මේ ඉලක්කම් තියන්නේ? මෙතන දසදහස්ස්ථානය, දහස්ස්ථානය කියලා ස්ථානීය අගයන් තියෙනවා.",
        hasInteractiveGate: false,
      },
      {
        id: "c4_beat_2",
        speaker: "Felix",
        dialogueText: "6 තියන්න කුඩාම වේදිකාව උඩින්! 6 කියන්නේ කුඩා අංකයක්නේ, ඒක අන්තිමටම තියමු!",
        hasInteractiveGate: false,
      },
      {
        id: "c4_beat_3",
        speaker: "Ella",
        dialogueText: "නැහැ ෆීලික්ස්! 68,507 හි 6 තියෙන්නේ දසදහස්ස්ථානයේ. ඒ කියන්නේ ඒකේ නිරූපිත අගය 60,000ක්!",
        hasInteractiveGate: false,
      },
      {
        id: "c4_beat_4",
        speaker: "Ella",
        dialogueText: "පුංචි යාළුවේ, අටවලා තියෙන උගුල්වලට අහුවෙන්නේ නැතිවෙන්න ඉලක්කම් නිවැරදි ස්ථානීය අගයන්වල තියන්න උදව් කරන්න!",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c5_unlocking_chest",
    title: "පාඩම 1 - සංකල්පය 5: නිධන් පෙට්ටිය විවෘත කිරීම (Unlocking the Chest)",
    conceptId: "c5_unlocking_chest",
    chapterNumber: 5,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "c5_beat_1",
        speaker: "Leo",
        dialogueText: "අපි ජයග්‍රහණයට ගොඩක් ළඟයි! ඒත් නිධන් පෙට්ටියේ ඉබි යතුර අහන්නේ 68,507 සංඛ්‍යාව විහිදුවා ලියන්න කියලයි. අපි ඒක කරන්නේ කොහොමද?",
        hasInteractiveGate: false,
      },
      {
        id: "c5_beat_2",
        speaker: "Felix",
        dialogueText: "පස්සට වෙන්න! මම මේ මිටියෙන් ගහලා යතුර කඩලා දාන්නම්! විහිදුවනවා කියන්නේ කඩන එකනේ!",
        hasInteractiveGate: false,
      },
      {
        id: "c5_beat_3",
        speaker: "Ella",
        dialogueText: "මිටිය පසෙකින් තියන්න ෆීලික්ස්! ගණිතයේදී සංඛ්‍යාවක් විහිදුවනවා කියන්නේ ඒක කඩන එක නෙවෙයි, ස්ථානීය අගයන්වලට වෙන් කර ලියන එකයි.",
        hasInteractiveGate: false,
      },
      {
        id: "c5_beat_4",
        speaker: "Ella",
        dialogueText: "ඒ කියන්නේ 68,507 විහිදුවා ලියන්නේ 60,000 + 8,000 + 500 + 0 + 7 ලෙසයි.",
        hasInteractiveGate: false,
      },
      {
        id: "c5_beat_5",
        speaker: "Ella",
        dialogueText: "එන්න යාළුවේ, අවසාන ඉබි යතුර අරින්න සංඛ්‍යාව විහිදුවා ලියන්න අපිට උදව් කරන්න!",
        hasInteractiveGate: false,
      },
    ],
  },

  // ─── LESSON 2: THE GREAT NUMBER TRAIN (5 CONCEPTS) ─────────────────────────
  {
    id: "quest_c1_number_train_station",
    title: "පාඩම 2 - සංකල්පය 1: පළමු නැවතුම – සංඛ්‍යා සසඳමු (Number Train Station)",
    conceptId: "c1_number_train_station",
    chapterNumber: 6,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "train_c1_beat_1",
        speaker: "Leo",
        dialogueText: "අපේ ඊළඟ ගමන කොහෙද කියලා මට හරිම කුතුහලයි!",
        hasInteractiveGate: false,
      },
      {
        id: "train_c1_beat_2",
        speaker: "Ella",
        dialogueText: "අපි අද යන්නේ මහා සංඛ්‍යා දුම්රියෙන්! දුම්රියට ගොඩවෙන්න සූදානම්ද?",
        hasInteractiveGate: false,
      },
      {
        id: "train_c1_beat_3",
        speaker: "Felix",
        dialogueText: "හහ්! සංඛ්‍යා තුනක් දැක්කාම විශාලම එක මම ඇස් දෙකෙන්ම තෝරන්නම්!",
        hasInteractiveGate: true,
        gateQuestion: "56, 28, 32 අතරින් විශාලම සංඛ්‍යාව කුමක්ද කියා තෝරන්න:",
        gateOptions: ["32 තෝරමු (ෆීලික්ස්ගේ තේරීම)", "56 තෝරමු (නිවැරදි තේරීම)"],
        gateCorrectIndex: 1,
      },
      {
        id: "train_c1_beat_4",
        speaker: "Ella",
        dialogueText: "ෆීලික්ස්, සංඛ්‍යාවක් විශාලද කුඩාද කියලා බලන්න නම් ඒවා හොඳින් සසඳන්න ඕනේ. අපි මුලින්ම සංඛ්‍යාවල ඉලක්කම් පිහිටි ස්ථාන බලමු!",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c2_number_train_ordering",
    title: "පාඩම 2 - සංකල්පය 2: දෙවන නැවතුම – සංඛ්‍යා පටිපාටිගත කරමු (Carriage Ordering)",
    conceptId: "c2_number_train_ordering",
    chapterNumber: 7,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "train_c2_beat_1",
        speaker: "Leo",
        dialogueText: "අපේ දුම්රියේ මැදිරි ටික අවුල් වෙලා! මේවා නිවැරදි පිළිවෙළට සකස් කරන්න ඕනේ.",
        hasInteractiveGate: false,
      },
      {
        id: "train_c2_beat_2",
        speaker: "Ella",
        dialogueText: "හරි! කුඩාම සංඛ්‍යාවේ සිට විශාලම සංඛ්‍යාව දක්වා සකස් කරන එකට \"ආරෝහණ පිළිවෙළ\" කියනවා. විශාලම සිට කුඩාම දක්වා \"අවරෝහණ පිළිවෙළ\" කියනවා.",
        hasInteractiveGate: false,
      },
      {
        id: "train_c2_beat_3",
        speaker: "Felix",
        dialogueText: "හහ්! මට නම් හිතෙන විදිහට දාන්න පුළුවන්!",
        hasInteractiveGate: true,
        gateQuestion: "47, 81, 74 ආරෝහණ පිළිවෙළ (කුඩාම සිට විශාලමට) තෝරන්න:",
        gateOptions: ["81, 74, 47 (ෆීලික්ස්ගේ තේරීම)", "47, 74, 81 (නිවැරදි තේරීම)"],
        gateCorrectIndex: 1,
      },
      {
        id: "train_c2_beat_4",
        speaker: "Ella",
        dialogueText: "ෆීලික්ස්, ඉක්මන් වෙන්න එපා! මුලින්ම සංඛ්‍යා සංසන්දනය කරමු. ඊට පස්සේ නිවැරදිව පටිපාටිගත කරන්න පුළුවන්.",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c3_digit_card_train",
    title: "පාඩම 2 - සංකල්පය 3: තෙවන නැවතුම – ඉලක්කම් පත්‍ර දුම්රිය (Digit Cards Train)",
    conceptId: "c3_digit_card_train",
    chapterNumber: 8,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "train_c3_beat_1",
        speaker: "Leo",
        dialogueText: "අපිට අලුත් දුම්රිය මැදිරි හමු වුණා! ඒත් ඒවායේ අංක තවම සකස් කරලා නැහැ.",
        hasInteractiveGate: false,
      },
      {
        id: "train_c3_beat_2",
        speaker: "Ella",
        dialogueText: "මෙන්න 0 සිට 9 දක්වා ඉලක්කම් පත්! මේවා භාවිත කරලා අපිට අලුත් සංඛ්‍යා හදන්න පුළුවන්.",
        hasInteractiveGate: false,
      },
      {
        id: "train_c3_beat_3",
        speaker: "Felix",
        dialogueText: "හහ්! මම නම් ඕනෑම ඉලක්කම් ටිකක් අරගෙන ලොකුම සංඛ්‍යාව හදනවා!",
        hasInteractiveGate: true,
        gateQuestion: "2, 5, 9, 7 භාවිත කර සෑදිය හැකි විශාලම සංඛ්‍යාව කුමක්ද?",
        gateOptions: ["2579 (ෆීලික්ස්ගේ තේරීම)", "9752 (නිවැරදි තේරීම)"],
        gateCorrectIndex: 1,
      },
      {
        id: "train_c3_beat_4",
        speaker: "Ella",
        dialogueText: "හොඳයි! හැබැයි ඉලක්කම්වල පිහිටීම වෙනස් කළොත් සංඛ්‍යාවේ අගයත් වෙනස් වෙනවා.",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c4_thousands_mountain",
    title: "පාඩම 2 - සංකල්පය 4: හතරවන නැවතුම – දහස් කඳුකරය (Thousands Mountain)",
    conceptId: "c4_thousands_mountain",
    chapterNumber: 9,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "train_c4_beat_1",
        speaker: "Leo",
        dialogueText: "වාව්! අපි දහස් කඳුකරයට ඇවිල්ලා!",
        hasInteractiveGate: false,
      },
      {
        id: "train_c4_beat_2",
        speaker: "Ella",
        dialogueText: "මෙතැන තියෙන සංඛ්‍යා 4 සහ 5 ඉලක්කම් සංඛ්‍යා. ඒවා හොඳින් සසඳන්න ඕනේ.",
        hasInteractiveGate: false,
      },
      {
        id: "train_c4_beat_3",
        speaker: "Felix",
        dialogueText: "මට නම් 18,508 ලොකුයි වගේ!",
        hasInteractiveGate: true,
        gateQuestion: "18,508, 33,240, 61,088 අතරින් විශාලම සංඛ්‍යාව කුමක්ද?",
        gateOptions: ["18,508 (ෆීලික්ස්ගේ තේරීම)", "61,088 (නිවැරදි තේරීම)"],
        gateCorrectIndex: 1,
      },
      {
        id: "train_c4_beat_4",
        speaker: "Ella",
        dialogueText: "පළමුව දසදහස්ස්ථානය බලමු. එතැනින් පටන් ගත්තොත් පහසුයි!",
        hasInteractiveGate: false,
      },
    ],
  },
  {
    id: "quest_c5_challenge_train",
    title: "පාඩම 2 - සංකල්පය 5: පස්වන නැවතුම – අභියෝග දුම්රිය (Challenge Train)",
    conceptId: "c5_challenge_train",
    chapterNumber: 10,
    status: "published",
    grade: 5,
    storySequence: [
      {
        id: "train_c5_beat_1",
        speaker: "Leo",
        dialogueText: "අපි දැන් සංඛ්‍යා අභියෝග දුම්රියට ළඟා වෙලා!",
        hasInteractiveGate: false,
      },
      {
        id: "train_c5_beat_2",
        speaker: "Ella",
        dialogueText: "මෙතැනින් පස්සේ ප්‍රශ්න ටික ටික අමාරු වෙනවා. අපි කලින් ඉගෙනගත්ත හැම දෙයක්ම භාවිත කරන්න වෙයි.",
        hasInteractiveGate: false,
      },
      {
        id: "train_c5_beat_3",
        speaker: "Felix",
        dialogueText: "අමාරුද? හහ්! මට නම් මේක ලේසියි!",
        hasInteractiveGate: true,
        gateQuestion: "12,450, 21,450, 19,999 අතරින් විශාලම සංඛ්‍යාව කුමක්ද?",
        gateOptions: ["19,999 (ෆීලික්ස්ගේ තේරීම)", "21,450 (නිවැරදි තේරීම)"],
        gateCorrectIndex: 1,
      },
      {
        id: "train_c5_beat_4",
        speaker: "Ella",
        dialogueText: "ඉක්මනින් තෝරන්න එපා Felix! පළමුව දසදහස්ස්ථානය බලමු.",
        hasInteractiveGate: false,
      },
    ],
  },
];
