import { Question } from "@/types";

export interface RevisionQuestionItem extends Question {
  conceptId: string;
  conceptTitleSi: string;
  conceptTitleEn: string;
  lessonId: string;
  lessonTitle: string;
  questionType: "comparison" | "ordering" | "expanded_form" | "mcq";
  hint1Si: string;
  hint2Si: string;
  explanationSi: string;
}

export const OFFICIAL_REVISION_QUESTIONS: RevisionQuestionItem[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // LESSON 1: රන් අඹ ගවේෂණය (THE QUEST FOR THE GOLDEN MANGO)
  // ═══════════════════════════════════════════════════════════════════════════

  // ─── CONCEPT 1: 9,999 දක්වා ස්ථානීය අගය හඳුනාගැනීම ───────────────────────
  {
    id: "rev_l1_c1_q1",
    questionText: "7,482 සංඛ්‍යාවේ '4' ඉලක්කම පිහිටි ස්ථානය සහ එහි ස්ථානීය අගය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["සියය (400)", "දහය (40)", "දහස (4,000)", "එක (4)"],
    correctAnswer: "සියය (400)",
    difficulty: 1,
    skillTag: "place_value_identification",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c1_jungle_map",
    conceptTitleSi: "1️⃣ 9,999 දක්වා සංඛ්‍යා හඳුනාගැනීම",
    conceptTitleEn: "Numbers up to 9,999",
    questionType: "mcq",
    hint1Si: "දකුණේ සිට වමට ස්ථාන ගණන් කරන්න: එකස්ථානය (2), දහස්ථානය (8), සියස්ථානය (4).",
    hint2Si: "4 ඉලක්කම සියස්ථානයේ ඇති බැවින් 4 × 100 = 400 වේ.",
    explanationSi: "7,482 සංඛ්‍යාවේ 4 පිහිටා ඇත්තේ සියස්ථානයේ වන අතර එහි ස්ථානීය අගය 400 වේ.",
  },
  {
    id: "rev_l1_c1_q2",
    questionText: "8,506 සංඛ්‍යාවේ දහස්ථානයේ ඇති ඉලක්කම කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["0", "5", "8", "6"],
    correctAnswer: "0",
    difficulty: 1,
    skillTag: "place_value_identification",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c1_jungle_map",
    conceptTitleSi: "1️⃣ 9,999 දක්වා සංඛ්‍යා හඳුනාගැනීම",
    conceptTitleEn: "Numbers up to 9,999",
    questionType: "mcq",
    hint1Si: "දකුණේ සිට දෙවනුව පිහිටි ස්ථානය දහස්ථානයයි.",
    hint2Si: "8,506 හි: එකස්ථානය 6, දහස්ථානය 0, සියස්ථානය 5, දහස්ස්ථානය 8 වේ.",
    explanationSi: "8,506 සංඛ්‍යාවේ දහස්ථානයේ 0 පිහිටා ඇත.",
  },
  {
    id: "rev_l1_c1_q3",
    questionText: "3,921 සහ 9,321 යන සංඛ්‍යාවල '9' ඉලක්කමේ ස්ථානීය අගයන් අතර වෙනස කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["9,000 සහ 900", "900 සහ 90", "9,000 සහ 90", "900 සහ 9,000"],
    correctAnswer: "900 සහ 9,000",
    difficulty: 2,
    skillTag: "place_value_identification",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c1_jungle_map",
    conceptTitleSi: "1️⃣ 9,999 දක්වා සංඛ්‍යා හඳුනාගැනීම",
    conceptTitleEn: "Numbers up to 9,999",
    questionType: "mcq",
    hint1Si: "3,921 හි 9 ඇත්තේ සියස්ථානයේය (900). 9,321 හි 9 ඇත්තේ දහස්ස්ථානයේය (9,000).",
    hint2Si: "පිළිවෙළින් 900 සහ 9,000 ලෙස හඳුනාගන්න.",
    explanationSi: "3,921 හි 9 හි අගය 900 වන අතර 9,321 හි 9 හි අගය 9,000 වේ.",
  },
  {
    id: "rev_l1_c1_q4",
    questionText: "'හයදහස් හතලිස් පහ' යන්න සම්මත ඉලක්කම්වලින් ලියූ විට ලැබෙන්නේ කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["6,045", "6,450", "6,405", "6,540"],
    correctAnswer: "6,045",
    difficulty: 1,
    skillTag: "place_value_word_form",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c1_jungle_map",
    conceptTitleSi: "1️⃣ 9,999 දක්වා සංඛ්‍යා හඳුනාගැනීම",
    conceptTitleEn: "Numbers up to 9,999",
    questionType: "mcq",
    hint1Si: "සියස්ථානයක් සඳහන් කර නැති බැවින් සියස්ථානයට 0 යොදන්න.",
    hint2Si: "දහස්ස්ථානයට 6, සියයට 0, දහයට 4, එකට 5 = 6,045.",
    explanationSi: "හයදහස් හතලිස් පහ = 6,045.",
  },

  // ─── CONCEPT 2: ඇබකසය හා ස්ථානීය අගය ─────────────────────────────────────
  {
    id: "rev_l1_c2_q1",
    questionText: "ඇබකසයක දහස් කණුවේ පබළු 4ක්, සියයේ කණුවේ පබළු 2ක්, දහයේ කණුවේ පබළු 3ක් සහ එකස්ථානයේ පබළු 5ක් ඇති විට සෑදෙන සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["4,235", "5,324", "4,325", "4,253"],
    correctAnswer: "4,235",
    difficulty: 1,
    skillTag: "abacus_representation",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c2_bead_river",
    conceptTitleSi: "2️⃣ ඇබකසයේ සංඛ්‍යා නිරූපණය",
    conceptTitleEn: "Abacus Representation",
    questionType: "mcq",
    hint1Si: "දහස් = 4, සියය = 2, දහය = 3, එක = 5 ලෙස වමේ සිට දකුණට ලියන්න.",
    hint2Si: "4 × 1000 + 2 × 100 + 3 × 10 + 5 × 1 = 4,235.",
    explanationSi: "පබළු ගණන අනුව සංඛ්‍යාව 4,235 වේ.",
  },
  {
    id: "rev_l1_c2_q2",
    questionText: "5,214 සංඛ්‍යාව නිරූපිත ඇබකසයක සියයේ කණුවට තවත් පබළු 3ක් දැමුවහොත් ලැබෙන නව සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["5,514", "5,244", "8,214", "5,217"],
    correctAnswer: "5,514",
    difficulty: 2,
    skillTag: "abacus_representation",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c2_bead_river",
    conceptTitleSi: "2️⃣ ඇබකසයේ සංඛ්‍යා නිරූපණය",
    conceptTitleEn: "Abacus Representation",
    questionType: "mcq",
    hint1Si: "සියයේ කණුවේ දැනට පබළු 2ක් ඇත. තවත් 3ක් එක් කළ විට 2 + 3 = 5ක් වේ.",
    hint2Si: "අනෙක් කණුවල අගයන් නොවෙනස්ව පවතී (5, 5, 1, 4).",
    explanationSi: "සියස්ථානයට 300ක් එකතු වූ විට 5,214 + 300 = 5,514 වේ.",
  },
  {
    id: "rev_l1_c2_q3",
    questionText: "8,703 සංඛ්‍යාව ඇබකසයක නිරූපණය කිරීමේදී කිසිදු පබළුවක් නොයෙදිය යුතු කණුව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["දහයේ කණුව (Tens)", "සියයේ කණුව (Hundreds)", "එකස්ථානයේ කණුව (Units)", "දහසේ කණුව (Thousands)"],
    correctAnswer: "දහයේ කණුව (Tens)",
    difficulty: 1,
    skillTag: "abacus_representation",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c2_bead_river",
    conceptTitleSi: "2️⃣ ඇබකසයේ සංඛ්‍යා නිරූපණය",
    conceptTitleEn: "Abacus Representation",
    questionType: "mcq",
    hint1Si: "0 අගය ඇත්තේ කුමන ස්ථානයේදැයි බලන්න.",
    hint2Si: "8,703 හි දහස්ථානයේ 0 ඇති බැවින් එම කණුව හිස්ව පවතී.",
    explanationSi: "දහයේ කණුවේ අගය 0 බැවින් කිසිදු පබළුවක් නොයොදයි.",
  },
  {
    id: "rev_l1_c2_q4",
    questionText: "ඇබකසයක දහසේ කණුවේ පමණක් පබළු 6ක් ඇති විට නිරූපණය වන සම්පූර්ණ අගය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["6,000", "600", "60,000", "60"],
    correctAnswer: "6,000",
    difficulty: 1,
    skillTag: "abacus_representation",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c2_bead_river",
    conceptTitleSi: "2️⃣ ඇබකසයේ සංඛ්‍යා නිරූපණය",
    conceptTitleEn: "Abacus Representation",
    questionType: "mcq",
    hint1Si: "දහසේ කණුවේ එක් පබළුවක අගය 1,000 කි.",
    hint2Si: "6 × 1,000 = 6,000.",
    explanationSi: "දහසේ කණුවේ පබළු 6 = 6,000.",
  },

  // ─── CONCEPT 3: 10,000 සිට 100,000 දක්වා විශාල සංඛ්‍යා ───────────────────
  {
    id: "rev_l1_c3_q1",
    questionText: "45,820 යන සංඛ්‍යාව වචනයෙන් නිවැරදිව කියවන ආකාරය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [
      "හතලිස් පන්දහස් අටසිය විස්ස",
      "හාරදහස් පන්සිය අසූ දෙක",
      "හතලිස් පන්සිය අටසිය විස්ස",
      "පන්සිය හතලිස් අටසිය විස්ස",
    ],
    correctAnswer: "හතලිස් පන්දහස් අටසිය විස්ස",
    difficulty: 1,
    skillTag: "large_numbers_reading",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c3_giants_gate",
    conceptTitleSi: "3️⃣ 10,000 සිට 100,000 දක්වා විශාල සංඛ්‍යා",
    conceptTitleEn: "Large Numbers 10,000 - 100,000",
    questionType: "mcq",
    hint1Si: "දහස් කාණ්ඩයේ ඇති සංඛ්‍යාව 45 (හතලිස් පහ) වේ.",
    hint2Si: "45,000 (හතලිස් පන්දහස්) + 820 (අටසිය විස්ස).",
    explanationSi: "45,820 = හතලිස් පන්දහස් අටසිය විස්ස.",
  },
  {
    id: "rev_l1_c3_q2",
    questionText: "83,619 සංඛ්‍යාවේ '8' ඉලක්කමේ ස්ථානීය අගය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["80,000 (අසූ දහස)", "8,000 (අටදහස)", "800 (අටසියය)", "800,000"],
    correctAnswer: "80,000 (අසූ දහස)",
    difficulty: 1,
    skillTag: "large_numbers_reading",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c3_giants_gate",
    conceptTitleSi: "3️⃣ 10,000 සිට 100,000 දක්වා විශාල සංඛ්‍යා",
    conceptTitleEn: "Large Numbers 10,000 - 100,000",
    questionType: "mcq",
    hint1Si: "8 පිහිටා ඇත්තේ දසදහස්ස්ථානයේය.",
    hint2Si: "8 × 10,000 = 80,000.",
    explanationSi: "83,619 හි 8 හි ස්ථානීය අගය 80,000 වේ.",
  },
  {
    id: "rev_l1_c3_q3",
    questionText: "99,999 ට පසු එන ඊළඟ නිඛිල සංඛ්‍යාව (Next Consecutive Number) කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["100,000 (එක් ලක්ෂය)", "100,999", "99,100", "10,000"],
    correctAnswer: "100,000 (එක් ලක්ෂය)",
    difficulty: 2,
    skillTag: "large_numbers_reading",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c3_giants_gate",
    conceptTitleSi: "3️⃣ 10,000 සිට 100,000 දක්වා විශාල සංඛ්‍යා",
    conceptTitleEn: "Large Numbers 10,000 - 100,000",
    questionType: "mcq",
    hint1Si: "99,999 ට 1ක් එකතු කරන්න.",
    hint2Si: "99,999 + 1 = 100,000 (ඉලක්කම් 6ක කුඩාම සංඛ්‍යාව).",
    explanationSi: "99,999 + 1 = 100,000 (එක් ලක්ෂය).",
  },
  {
    id: "rev_l1_c3_q4",
    questionText: "පුස්තකාලයක පොත් 32,450ක් සහ තවත් පුස්තකාලයක පොත් 32,540ක් ඇත. වැඩිම පොත් සංඛ්‍යාවක් ඇති පුස්තකාලයේ පොත් ගණන කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["32,540", "32,450", "දෙකම සමානයි", "32,054"],
    correctAnswer: "32,540",
    difficulty: 2,
    skillTag: "large_numbers_reading",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c3_giants_gate",
    conceptTitleSi: "3️⃣ 10,000 සිට 100,000 දක්වා විශාල සංඛ්‍යා",
    conceptTitleEn: "Large Numbers 10,000 - 100,000",
    questionType: "mcq",
    hint1Si: "දහස් කාණ්ඩ දෙකම 32 වේ. සියස්ථාන සංසන්දනය කරන්න (400 vs 500).",
    hint2Si: "500 > 400 බැවින් 32,540 විශාල වේ.",
    explanationSi: "32,540 > 32,450 බැවින් වැඩිම පොත් සංඛ්‍යාව 32,540 කි.",
  },

  // ─── CONCEPT 4: දසදහස්ස්ථානය දක්වා ස්ථානීය අගයන් ─────────────────────────
  {
    id: "rev_l1_c4_q1",
    questionText: "64,820 [ ? ] 64,280 හිස්තැනට ගැළපෙන නිවැරදි සංසන්දන ලකුණ කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [">", "<", "=", "+"],
    correctAnswer: ">",
    difficulty: 1,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c4_crystal_cave",
    conceptTitleSi: "4️⃣ දසදහස්ස්ථානය දක්වා ස්ථානීය අගයන්",
    conceptTitleEn: "Place Values up to Ten-Thousands",
    questionType: "comparison",
    hint1Si: "දසදහස් (6) සහ දහස් (4) ස්ථාන සමාන වේ. සියස්ථානය බලන්න: 800 vs 200.",
    hint2Si: "800 > 200 බැවින් 64,820 > 64,280 වේ.",
    explanationSi: "සියස්ථානයේ 8 > 2 බැවින් 64,820 > 64,280 වේ.",
  },
  {
    id: "rev_l1_c4_q2",
    questionText: "72,405 සංඛ්‍යාවේ 7 හි ස්ථානීය අගය, 27,405 සංඛ්‍යාවේ 7 හි ස්ථානීය අගයට වඩා කොපමණ විශාලද?",
    subject: "Maths",
    grade: 5,
    options: [
      "70,000 සහ 7,000 (10 ගුණයකින් විශාලයි)",
      "7,000 සහ 700",
      "70,000 සහ 700",
      "දෙකම එක සමානයි",
    ],
    correctAnswer: "70,000 සහ 7,000 (10 ගුණයකින් විශාලයි)",
    difficulty: 3,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c4_crystal_cave",
    conceptTitleSi: "4️⃣ දසදහස්ස්ථානය දක්වා ස්ථානීය අගයන්",
    conceptTitleEn: "Place Values up to Ten-Thousands",
    questionType: "mcq",
    hint1Si: "72,405 හි 7 ඇත්තේ දසදහස්ස්ථානයේය (70,000). 27,405 හි 7 ඇත්තේ දහස්ස්ථානයේය (7,000).",
    hint2Si: "70,000 යනු 7,000 මෙන් 10 ගුණයකි.",
    explanationSi: "70,000 සහ 7,000 වන අතර එය 10 ගුණයක අගයකි.",
  },
  {
    id: "rev_l1_c4_q3",
    questionText: "'5' ඉලක්කමෙන් ආරම්භ වන කුඩාම පස්අංක සංඛ්‍යාව (5-digit number) කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["50,000", "50,001", "51,111", "55,555"],
    correctAnswer: "50,000",
    difficulty: 2,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c4_crystal_cave",
    conceptTitleSi: "4️⃣ දසදහස්ස්ථානය දක්වා ස්ථානීය අගයන්",
    conceptTitleEn: "Place Values up to Ten-Thousands",
    questionType: "mcq",
    hint1Si: "කුඩාම අගය සෑදීමට ඉතිරි ස්ථාන සියල්ලටම 0 යොදන්න.",
    hint2Si: "5 + 0 + 0 + 0 + 0 = 50,000.",
    explanationSi: "5 න් ආරම්භ වන කුඩාම පස්අංක සංඛ්‍යාව 50,000 වේ.",
  },
  {
    id: "rev_l1_c4_q4",
    questionText: "90,412 සංඛ්‍යාවේ '0' ඉලක්කම පිහිටා ඇති ස්ථානය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["දහස්ස්ථානය (Thousands)", "සියස්ථානය (Hundreds)", "දහස්ථානය (Tens)", "දසදහස්ස්ථානය (Ten-Thousands)"],
    correctAnswer: "දහස්ස්ථානය (Thousands)",
    difficulty: 1,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c4_crystal_cave",
    conceptTitleSi: "4️⃣ දසදහස්ස්ථානය දක්වා ස්ථානීය අගයන්",
    conceptTitleEn: "Place Values up to Ten-Thousands",
    questionType: "mcq",
    hint1Si: "දකුණේ සිට: 2 (එක), 1 (දහය), 4 (සියය), 0 (දහස).",
    hint2Si: "0 පිහිටා ඇත්තේ දහස්ස්ථානයේය.",
    explanationSi: "90,412 හි 0 පිහිටා ඇත්තේ දහස්ස්ථානයේය.",
  },

  // ─── CONCEPT 5: සංඛ්‍යා විහිදුවා ලිවීම (EXPANDED FORM) ────────────────────
  {
    id: "rev_l1_c5_q1",
    questionText: "53,892 සංඛ්‍යාව විහිදුවා ලියූ නිවැරදි ආකාරය තෝරන්න.",
    subject: "Maths",
    grade: 5,
    options: [
      "50,000 + 3,000 + 800 + 90 + 2",
      "5,000 + 300 + 80 + 9 + 2",
      "50,000 + 300 + 80 + 90 + 2",
      "500,000 + 30,000 + 800 + 90 + 2",
    ],
    correctAnswer: "50,000 + 3,000 + 800 + 90 + 2",
    difficulty: 1,
    skillTag: "expanded_form",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c5_unlocking_chest",
    conceptTitleSi: "5️⃣ සංඛ්‍යා විහිදුවා ලිවීම",
    conceptTitleEn: "Expanded Form Notation",
    questionType: "expanded_form",
    hint1Si: "එක් එක් ඉලක්කමේ ස්ථානීය අගයන් ලියා එකතු කිරීමේ ලකුණින් (+) සම්බන්ධ කරන්න.",
    hint2Si: "50,000 + 3,000 + 800 + 90 + 2 = 53,892.",
    explanationSi: "53,892 = 50,000 + 3,000 + 800 + 90 + 2.",
  },
  {
    id: "rev_l1_c5_q2",
    questionText: "70,000 + 400 + 50 + 6 එකතු කළ විට ලැබෙන සම්මත සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["70,456", "74,056", "74,560", "7,456"],
    correctAnswer: "70,456",
    difficulty: 2,
    skillTag: "expanded_form",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c5_unlocking_chest",
    conceptTitleSi: "5️⃣ සංඛ්‍යා විහිදුවා ලිවීම",
    conceptTitleEn: "Expanded Form Notation",
    questionType: "expanded_form",
    hint1Si: "දහස්ස්ථානයේ අගයක් සඳහන් නොවන බැවින් දහස්ස්ථානයට 0 යොදන්න.",
    hint2Si: "දසදහස=7, දහස=0, සියය=4, දහය=5, එක=6 ➔ 70,456.",
    explanationSi: "70,000 + 400 + 50 + 6 = 70,456.",
  },
  {
    id: "rev_l1_c5_q3",
    questionText: "84,321 = 80,000 + [ ? ] + 300 + 20 + 1 හිස්තැනට ගැළපෙන අගය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["4,000", "40,000", "400", "40"],
    correctAnswer: "4,000",
    difficulty: 2,
    skillTag: "expanded_form",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c5_unlocking_chest",
    conceptTitleSi: "5️⃣ සංඛ්‍යා විහිදුවා ලිවීම",
    conceptTitleEn: "Expanded Form Notation",
    questionType: "expanded_form",
    hint1Si: "84,321 හි '4' ඉලක්කමේ ස්ථානීය අගය සොයන්න.",
    hint2Si: "4 ඇත්තේ දහස්ස්ථානයේ බැවින් 4 × 1,000 = 4,000 වේ.",
    explanationSi: "නැතිවී ඇති පදය 4,000 වේ.",
  },
  {
    id: "rev_l1_c5_q4",
    questionText: "90,005 සංඛ්‍යාව විහිදුවා ලියූ නිවැරදි ආකාරය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["90,000 + 5", "9,000 + 5", "90,000 + 50", "900,000 + 5"],
    correctAnswer: "90,000 + 5",
    difficulty: 1,
    skillTag: "expanded_form",
    lessonId: "math_grade5_01",
    lessonTitle: "රන් අඹ ගවේෂණය (The Quest for the Golden Mango)",
    conceptId: "c5_unlocking_chest",
    conceptTitleSi: "5️⃣ සංඛ්‍යා විහිදුවා ලිවීම",
    conceptTitleEn: "Expanded Form Notation",
    questionType: "expanded_form",
    hint1Si: "ශුන්‍ය (0) ඇති ස්ථාන (දහස්, සියය, දහය) විහිදුවා ලිවීමේදී සඳහන් කිරීම අත්‍යවශ්‍ය නොවේ.",
    hint2Si: "90,000 + 5 = 90,005.",
    explanationSi: "90,005 = 90,000 + 5.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LESSON 2: මහා සංඛ්‍යා දුම්රිය (THE GREAT NUMBER TRAIN)
  // ═══════════════════════════════════════════════════════════════════════════

  // ─── CONCEPT 6: 2-Digit & 3-Digit Number Comparison ───────────────────────
  {
    id: "rev_l2_c1_q1",
    questionText: "485 [ ? ] 458 හිස්තැනට ගැළපෙන නිවැරදි සංසන්දන ලකුණ කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [">", "<", "=", "+"],
    correctAnswer: ">",
    difficulty: 1,
    skillTag: "compare_numbers",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c1_number_train_station",
    conceptTitleSi: "1️⃣ පළමු නැවතුම – සංඛ්‍යා සසඳමු",
    conceptTitleEn: "Comparing 2-Digit & 3-Digit Numbers",
    questionType: "comparison",
    hint1Si: "සියස්ථාන දෙකම 4 වේ. දහස්ථාන බලන්න: 8 vs 5.",
    hint2Si: "80 > 50 බැවින් 485 > 458 වේ.",
    explanationSi: "දහස්ථානයේ 8 > 5 බැවින් 485 > 458 වේ.",
  },
  {
    id: "rev_l2_c1_q2",
    questionText: "792 [ ? ] 792 හිස්තැනට ගැළපෙන සංකේතය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["=", ">", "<", "≠"],
    correctAnswer: "=",
    difficulty: 1,
    skillTag: "compare_numbers",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c1_number_train_station",
    conceptTitleSi: "1️⃣ පළමු නැවතුම – සංඛ්‍යා සසඳමු",
    conceptTitleEn: "Comparing 2-Digit & 3-Digit Numbers",
    questionType: "comparison",
    hint1Si: "සංඛ්‍යා දෙකේම සියලුම ඉලක්කම් සමාන වේ.",
    hint2Si: "792 සමානයි 792 (=).",
    explanationSi: "සංඛ්‍යා දෙකම සමාන බැවින් = ලකුණ යෙදේ.",
  },
  {
    id: "rev_l2_c1_q3",
    questionText: "369 [ ? ] 639 හිස්තැනට ගැළපෙන සංකේතය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["<", ">", "=", "-"],
    correctAnswer: "<",
    difficulty: 1,
    skillTag: "compare_numbers",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c1_number_train_station",
    conceptTitleSi: "1️⃣ පළමු නැවතුම – සංඛ්‍යා සසඳමු",
    conceptTitleEn: "Comparing 2-Digit & 3-Digit Numbers",
    questionType: "comparison",
    hint1Si: "ඉහළම ස්ථානය වන සියස්ථානය සංසන්දනය කරන්න (300 vs 600).",
    hint2Si: "300 < 600 බැවින් 369 < 639 වේ.",
    explanationSi: "සියස්ථානයේ 3 < 6 බැවින් 369 < 639 වේ.",
  },
  {
    id: "rev_l2_c1_q4",
    questionText: "845, 854, 485, 584 යන සංඛ්‍යා අතරින් විශාලම සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["854", "845", "584", "485"],
    correctAnswer: "854",
    difficulty: 2,
    skillTag: "largest_number",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c1_number_train_station",
    conceptTitleSi: "1️⃣ පළමු නැවතුම – සංඛ්‍යා සසඳමු",
    conceptTitleEn: "Comparing 2-Digit & 3-Digit Numbers",
    questionType: "mcq",
    hint1Si: "සියස්ථානයේ 8 ඇති සංඛ්‍යා දෙක බලන්න: 845 සහ 854.",
    hint2Si: "854 හි දහස්ථානයේ 5 > 4 බැවින් 854 විශාලම සංඛ්‍යාවයි.",
    explanationSi: "විශාලම සංඛ්‍යාව 854 වේ.",
  },

  // ─── CONCEPT 7: දුම්රිය මැදිරි පේළිගත කිරීම (ORDERING) ────────────────────
  {
    id: "rev_l2_c2_q1",
    questionText: "320, 185, 490, 275 යන සංඛ්‍යා ආරෝහණ පිළිවෙළට (කුඩා ➔ විශාල) සකසන්න.",
    subject: "Maths",
    grade: 5,
    options: [
      "185, 275, 320, 490",
      "490, 320, 275, 185",
      "185, 320, 275, 490",
      "275, 185, 320, 490",
    ],
    correctAnswer: "185, 275, 320, 490",
    difficulty: 2,
    skillTag: "number_ordering",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c2_number_train_ordering",
    conceptTitleSi: "2️⃣ දෙවන නැවතුම – සංඛ්‍යා පටිපාටිගත කරමු",
    conceptTitleEn: "Ascending & Descending Ordering",
    questionType: "ordering",
    hint1Si: "කුඩාම සංඛ්‍යාවෙන් ආරම්භ කරන්න (185).",
    hint2Si: "ඉන්පසු: 275 ➔ 320 ➔ 490.",
    explanationSi: "ආරෝහණ පිළිවෙළ: 185, 275, 320, 490.",
  },
  {
    id: "rev_l2_c2_q2",
    questionText: "4,520, 4,810, 4,190, 4,600 යන සංඛ්‍යා අවරෝහණ පිළිවෙළට (විශාල ➔ කුඩා) සකසන්න.",
    subject: "Maths",
    grade: 5,
    options: [
      "4,810, 4,600, 4,520, 4,190",
      "4,190, 4,520, 4,600, 4,810",
      "4,810, 4,520, 4,600, 4,190",
      "4,600, 4,810, 4,520, 4,190",
    ],
    correctAnswer: "4,810, 4,600, 4,520, 4,190",
    difficulty: 2,
    skillTag: "number_ordering",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c2_number_train_ordering",
    conceptTitleSi: "2️⃣ දෙවන නැවතුම – සංඛ්‍යා පටිපාටිගත කරමු",
    conceptTitleEn: "Ascending & Descending Ordering",
    questionType: "ordering",
    hint1Si: "අවරෝහණ යනු විශාලම සංඛ්‍යාවේ සිට කුඩාම සංඛ්‍යාව දක්වායි.",
    hint2Si: "විශාලම සංඛ්‍යාව 4,810 ➔ 4,600 ➔ 4,520 ➔ 4,190.",
    explanationSi: "අවරෝහණ පිළිවෙළ: 4,810, 4,600, 4,520, 4,190.",
  },
  {
    id: "rev_l2_c2_q3",
    questionText: "25,100, 25,010, 25,101 යන සංඛ්‍යා ආරෝහණ පිළිවෙළට පෙළගැස්වූ විට ලැබෙන්නේ කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [
      "25,010, 25,100, 25,101",
      "25,101, 25,100, 25,010",
      "25,010, 25,101, 25,100",
      "25,100, 25,010, 25,101",
    ],
    correctAnswer: "25,010, 25,100, 25,101",
    difficulty: 3,
    skillTag: "number_ordering",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c2_number_train_ordering",
    conceptTitleSi: "2️⃣ දෙවන නැවතුම – සංඛ්‍යා පටිපාටිගත කරමු",
    conceptTitleEn: "Ascending & Descending Ordering",
    questionType: "ordering",
    hint1Si: "කුඩාම සංඛ්‍යාව 25,010 (සියස්ථානයේ 0 ඇත).",
    hint2Si: "25,100 ට පසු 25,101 එයි.",
    explanationSi: "ආරෝහණ පිළිවෙළ: 25,010, 25,100, 25,101.",
  },
  {
    id: "rev_l2_c2_q4",
    questionText: "8,200, 8,900, 8,450, 8,100 යන සංඛ්‍යා අවරෝහණ පිළිවෙළට ලිවීමේදී 3 වන ස්ථානයට එන සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["8,200", "8,450", "8,900", "8,100"],
    correctAnswer: "8,200",
    difficulty: 2,
    skillTag: "number_ordering",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c2_number_train_ordering",
    conceptTitleSi: "2️⃣ දෙවන නැවතුම – සංඛ්‍යා පටිපාටිගත කරමු",
    conceptTitleEn: "Ascending & Descending Ordering",
    questionType: "mcq",
    hint1Si: "පිළිවෙළ: 1. 8,900 ➔ 2. 8,450 ➔ 3. 8,200 ➔ 4. 8,100.",
    hint2Si: "තුන්වන සංඛ්‍යාව 8,200 වේ.",
    explanationSi: "අවරෝහණ පිළිවෙළේ 3 වන සංඛ්‍යාව 8,200 වේ.",
  },

  // ─── CONCEPT 8: ඉලක්කම් කාඩ්පත් මඟින් සංඛ්‍යා නිර්මාණය ───────────────────
  {
    id: "rev_l2_c3_q1",
    questionText: "3, 8, 1, 7 යන ඉලක්කම් කාඩ්පත් සියල්ල එක් වරක් පමණක් භාවිත කර සෑදිය හැකි විශාලම සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["8,731", "8,713", "7,831", "8,371"],
    correctAnswer: "8,731",
    difficulty: 2,
    skillTag: "digit_builder",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c3_digit_cards",
    conceptTitleSi: "3️⃣ තෙවන නැවතුම – ඉලක්කම් පත්‍ර දුම්රිය",
    conceptTitleEn: "0-9 Digit Card Construction",
    questionType: "mcq",
    hint1Si: "විශාලම සංඛ්‍යාව සෑදීමට ඉලක්කම් විශාලම අගයේ සිට කුඩාම අගය දක්වා (අවරෝහණව) පෙළගස්වන්න.",
    hint2Si: "8 ➔ 7 ➔ 3 ➔ 1 = 8,731.",
    explanationSi: "විශාලම සංඛ්‍යාව 8,731 වේ.",
  },
  {
    id: "rev_l2_c3_q2",
    questionText: "5, 0, 9, 2 යන කාඩ්පත් භාවිත කර සෑදිය හැකි කුඩාම සිව්අංක සංඛ්‍යාව (4-digit number) කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["2,059", "0,259", "2,509", "2,095"],
    correctAnswer: "2,059",
    difficulty: 2,
    skillTag: "digit_builder",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c3_digit_cards",
    conceptTitleSi: "3️⃣ තෙවන නැවතුම – ඉලක්කම් පත්‍ර දුම්රිය",
    conceptTitleEn: "0-9 Digit Card Construction",
    questionType: "mcq",
    hint1Si: "සිව්අංක සංඛ්‍යාවක් සෑදීමේදී පළමු ඉලක්කමට 0 යෙදිය නොහැක. 0 හැර කුඩාම ඉලක්කම වන 2 මුලට යොදන්න.",
    hint2Si: "දෙවනුව 0 යොදා ඉතිරි ඉලක්කම් ආරෝහණව ලියන්න: 2 ➔ 0 ➔ 5 ➔ 9 = 2,059.",
    explanationSi: "කුඩාම සිව්අංක සංඛ්‍යාව 2,059 වේ.",
  },
  {
    id: "rev_l2_c3_q3",
    questionText: "6, 4, 0, 9, 2 යන කාඩ්පත් 5ම භාවිත කර සෑදිය හැකි විශාලම පස්අංක සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["96,420", "96,402", "94,620", "69,420"],
    correctAnswer: "96,420",
    difficulty: 2,
    skillTag: "digit_builder",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c3_digit_cards",
    conceptTitleSi: "3️⃣ තෙවන නැවතුම – ඉලක්කම් පත්‍ර දුම්රිය",
    conceptTitleEn: "0-9 Digit Card Construction",
    questionType: "mcq",
    hint1Si: "ඉලක්කම් විශාලම අගයේ සිට කුඩාම අගය දක්වා ලියන්න.",
    hint2Si: "9 ➔ 6 ➔ 4 ➔ 2 ➔ 0 = 96,420.",
    explanationSi: "විශාලම සංඛ්‍යාව 96,420 වේ.",
  },
  {
    id: "rev_l2_c3_q4",
    questionText: "7, 3, 5, 0, 1 යන කාඩ්පත් භාවිත කර සෑදිය හැකි කුඩාම පස්අංක සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["10,357", "01,357", "10,537", "13,057"],
    correctAnswer: "10,357",
    difficulty: 3,
    skillTag: "digit_builder",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c3_digit_cards",
    conceptTitleSi: "3️⃣ තෙවන නැවතුම – ඉලක්කම් පත්‍ර දුම්රිය",
    conceptTitleEn: "0-9 Digit Card Construction",
    questionType: "mcq",
    hint1Si: "0 හැර කුඩාම ඉලක්කම වන 1 මුලට තබා දෙවනුව 0 යොදන්න.",
    hint2Si: "ඉතිරි ඉලක්කම් කුඩා අගයේ සිට ලියන්න: 1 ➔ 0 ➔ 3 ➔ 5 ➔ 7 = 10,357.",
    explanationSi: "කුඩාම පස්අංක සංඛ්‍යාව 10,357 වේ.",
  },

  // ─── CONCEPT 9: විශාල සංඛ්‍යා කඳු තරණය (MOUNTAIN COMPARISON) ─────────────
  {
    id: "rev_l2_c4_q1",
    questionText: "පිදුරුතලාගල කඳු මුදුනේ උස මීටර් 2,524 කි. කිරගල්පොත්ත කන්දේ උස මීටර් 2,395 කි. මෙම උසවල් සංසන්දනය කළ නිවැරදි ප්‍රකාශය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [
      "2,524 > 2,395 (පිදුරුතලාගල උසින් වැඩියි)",
      "2,524 < 2,395 (කිරගල්පොත්ත උසින් වැඩියි)",
      "2,524 = 2,395 (දෙකම සමානයි)",
      "2,395 > 2,524",
    ],
    correctAnswer: "2,524 > 2,395 (පිදුරුතලාගල උසින් වැඩියි)",
    difficulty: 1,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c4_mountain_tracks",
    conceptTitleSi: "4️⃣ සිව්වන නැවතුම – සංඛ්‍යා කඳු තරණය",
    conceptTitleEn: "Mountain Track Comparison",
    questionType: "comparison",
    hint1Si: "සියස්ථාන සංසන්දනය කරන්න: 500 > 300.",
    hint2Si: "2,524 > 2,395.",
    explanationSi: "2,524 > 2,395 වන බැවින් පිදුරුතලාගල උසින් වැඩිය.",
  },
  {
    id: "rev_l2_c4_q2",
    questionText: "A නගරයේ ජනගහනය 68,400 කි. B නගරයේ ජනගහනය 68,040 කි. වැඩි ජනගහනයක් ඇති නගරය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["A නගරය (68,400)", "B නගරය (68,040)", "දෙකම සමානයි", "තීරණය කළ නොහැක"],
    correctAnswer: "A නගරය (68,400)",
    difficulty: 2,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c4_mountain_tracks",
    conceptTitleSi: "4️⃣ සිව්වන නැවතුම – සංඛ්‍යා කඳු තරණය",
    conceptTitleEn: "Mountain Track Comparison",
    questionType: "mcq",
    hint1Si: "දහස් කාණ්ඩය (68) සමාන වේ. සියස්ථාන බලන්න: 400 vs 0.",
    hint2Si: "400 > 0 බැවින් 68,400 > 68,040 වේ.",
    explanationSi: "A නගරයේ ජනගහනය (68,400) වැඩිය.",
  },
  {
    id: "rev_l2_c4_q3",
    questionText: "54,321 සහ 54,231 යන සංඛ්‍යා අතරින් කුඩා සංඛ්‍යාව කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["54,231", "54,321", "දෙකම සමානයි", "54,123"],
    correctAnswer: "54,231",
    difficulty: 2,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c4_mountain_tracks",
    conceptTitleSi: "4️⃣ සිව්වන නැවතුම – සංඛ්‍යා කඳු තරණය",
    conceptTitleEn: "Mountain Track Comparison",
    questionType: "mcq",
    hint1Si: "සියස්ථානයේ කුඩාම ඉලක්කම ඇති සංඛ්‍යාව තෝරන්න (200 vs 300).",
    hint2Si: "54,231 < 54,321.",
    explanationSi: "කුඩා සංඛ්‍යාව 54,231 වේ.",
  },
  {
    id: "rev_l2_c4_q4",
    questionText: "'89,990 < 90,000' යන ප්‍රකාශය සත්‍යද (True) අසත්‍යද (False)?",
    subject: "Maths",
    grade: 5,
    options: ["සත්‍ය වේ (True)", "අසත්‍ය වේ (False)"],
    correctAnswer: "සත්‍ය වේ (True)",
    difficulty: 1,
    skillTag: "place_value_comparison",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c4_mountain_tracks",
    conceptTitleSi: "4️⃣ සිව්වන නැවතුම – සංඛ්‍යා කඳු තරණය",
    conceptTitleEn: "Mountain Track Comparison",
    questionType: "comparison",
    hint1Si: "89,990 ට තව 10ක් එක් කළ විට 90,000 ලැබේ.",
    hint2Si: "එබැවින් 89,990 අගයෙන් කුඩාය.",
    explanationSi: "89,990 < 90,000 ප්‍රකාශය සත්‍ය වේ.",
  },

  // ─── CONCEPT 10: මහා දුම්රිය ශූරතාව (CHAMPIONSHIP MASTERY) ────────────────
  {
    id: "rev_l2_c5_q1",
    questionText: "74,532 සංඛ්‍යාව පිළිබඳ සත්‍ය ප්‍රකාශය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [
      "7 හි ස්ථානීය අගය 70,000 වේ",
      "4 හි ස්ථානීය අගය 400 වේ",
      "5 හි ස්ථානීය අගය 5,000 වේ",
      "3 හි ස්ථානීය අගය 300 වේ",
    ],
    correctAnswer: "7 හි ස්ථානීය අගය 70,000 වේ",
    difficulty: 2,
    skillTag: "place_value_identification",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c5_championship_flag",
    conceptTitleSi: "5️⃣ අවසන් නැවතුම – මහා දුම්රිය ශූරතාව",
    conceptTitleEn: "Championship Mixed Mastery",
    questionType: "mcq",
    hint1Si: "7 පිහිටා ඇත්තේ දසදහස්ස්ථානයේය (7 × 10,000 = 70,000).",
    hint2Si: "අනෙක් ප්‍රකාශ සියල්ල අසත්‍ය වේ.",
    explanationSi: "7 හි ස්ථානීය අගය 70,000 වේ.",
  },
  {
    id: "rev_l2_c5_q2",
    questionText: "60,804 සංඛ්‍යාව විහිදුවා ලියූ නිවැරදි ආකාරය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [
      "60,000 + 800 + 4",
      "6,000 + 800 + 4",
      "60,000 + 80 + 4",
      "600,000 + 800 + 4",
    ],
    correctAnswer: "60,000 + 800 + 4",
    difficulty: 2,
    skillTag: "expanded_form",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c5_championship_flag",
    conceptTitleSi: "5️⃣ අවසන් නැවතුම – මහා දුම්රිය ශූරතාව",
    conceptTitleEn: "Championship Mixed Mastery",
    questionType: "expanded_form",
    hint1Si: "දහස් සහ දහස්ථාන 0 බැවින් 60,000 + 800 + 4 වේ.",
    hint2Si: "60,804 = 60,000 + 800 + 4.",
    explanationSi: "60,804 = 60,000 + 800 + 4.",
  },
  {
    id: "rev_l2_c5_q3",
    questionText: "95,400 [ ? ] 95,040 හිස්තැනට ගැළපෙන නිවැරදි සංකේතය කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: [">", "<", "=", "+"],
    correctAnswer: ">",
    difficulty: 2,
    skillTag: "compare_numbers",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c5_championship_flag",
    conceptTitleSi: "5️⃣ අවසන් නැවතුම – මහා දුම්රිය ශූරතාව",
    conceptTitleEn: "Championship Mixed Mastery",
    questionType: "comparison",
    hint1Si: "සියස්ථානය බලන්න: 400 vs 0.",
    hint2Si: "400 > 0 බැවින් 95,400 > 95,040 වේ.",
    explanationSi: "95,400 > 95,040 වේ.",
  },
  {
    id: "rev_l2_c5_q4",
    questionText: "4, 7, 2, 9 යන ඉලක්කම් කාඩ්පත් භාවිත කර සෑදිය හැකි කුඩාම ඉරට්ටේ සංඛ්‍යාව (Smallest Even Number) කුමක්ද?",
    subject: "Maths",
    grade: 5,
    options: ["2,794", "2,479", "2,974", "4,792"],
    correctAnswer: "2,794",
    difficulty: 3,
    skillTag: "digit_builder",
    lessonId: "math_grade5_02",
    lessonTitle: "මහා සංඛ්‍යා දුම්රිය (The Great Number Train)",
    conceptId: "c5_championship_flag",
    conceptTitleSi: "5️⃣ අවසන් නැවතුම – මහා දුම්රිය ශූරතාව",
    conceptTitleEn: "Championship Mixed Mastery",
    questionType: "mcq",
    hint1Si: "ඉරට්ටේ සංඛ්‍යාවක් වීමට අග ඉලක්කම 2 හෝ 4 විය යුතුය.",
    hint2Si: "කුඩාම අගය සෑදීමට මුලට 2 තබා අගට 4 යොදන්න: 2 ➔ 7 ➔ 9 ➔ 4 = 2,794.",
    explanationSi: "කුඩාම ඉරට්ටේ සංඛ්‍යාව 2,794 වේ.",
  },
];
