import { LessonModule, LessonConcept, ExerciseStep } from "@/types";

export const OFFICIAL_GRADE_5_LESSONS: LessonModule[] = [
  // ─── LESSON 1: THE GOLDEN MANGO QUEST (Numbers & Place Value) ───────────────
  {
    id: "lesson_1_golden_mango",
    title: "පාඩම 1: රන් අඹ ගෙඩිය සොයා ගමන (Numbers & Place Value)",
    lessonNumber: 1,
    description: "99,999 දක්වා සංඛ්‍යා කියවීම, ලිවීම, 4-ස්ථානීය හා 5-ස්ථානීය අගය, විහිදුවා ලිවීම සහ අබාකස්",
    conceptId: "golden_mango_quest",
    status: "published",
    grade: 5,
    concepts: [
      // ─── CONCEPT 1: JUNGLE MAP — Numbers up to 9,999 ───
      {
        id: "c1_jungle_map",
        conceptId: "c1_jungle_map",
        title: "සංකල්පය 1: අංක කැලෑ සිතියම",
        subtitle: "9,999 දක්වා සංඛ්‍යා කියවීම හා ලිවීම",
        learningObjective: "9,999 දක්වා සංඛ්‍යා කියවීම හා ලිවීම",
        orderIndex: 1,
        questions: [
          {
            id: "c1_q1",
            conceptId: "c1_jungle_map",
            interactionType: "multipleChoice",
            questionText: "84 කියවන ආකාරය තෝරන්න.",
            options: ["අටසිය හතර", "අසූ හතර", "අසූ හත", "අටසිය හතළිහ"],
            correctAnswer: "අසූ හතර",
            hintLevel1: "84 සංඛ්‍යාවේ දහයස්ථානයේ 8 ද (අසූ), ඒකස්ථානයේ 4 ද (හතර) ඇත.",
            hintLevel2: "80 (අසූ) + 4 (හතර) = 84 (අසූ හතර).",
            workedSolution: "84 හි 80 = අසූ, 4 = හතර. එම නිසා 84 කියවන්නේ 'අසූ හතර' ලෙසයි.",
            skillTag: "number_reading",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c1_q2",
            conceptId: "c1_jungle_map",
            interactionType: "numericInput",
            questionText: "\"තුන් දහස් හාරසිය විසි එක\" ඉලක්කම් වලින් ලියන්න.",
            correctAnswer: "3421",
            hintLevel1: "තුන් දහස් = 3000, හාරසිය = 400, විසි එක = 21.",
            hintLevel2: "3000 + 400 + 20 + 1 = 3421.",
            workedSolution: "තුන් දහස් (3000) + හාරසිය (400) + විසි එක (21) = 3421.",
            skillTag: "number_writing",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c1_q3",
            conceptId: "c1_jungle_map",
            interactionType: "digitBuilder",
            questionText: "1, 3, 6, 4 ඉලක්කම් 4 භාවිතයෙන් සාදාගත හැකි විශාලතම සංඛ්‍යාව සාදන්න.",
            correctAnswer: "6431",
            options: ["6431", "6341", "4631", "6413"],
            hintLevel1: "විශාලතම සංඛ්‍යාව සෑදීමට විශාලතම ඉලක්කම (6) දහස්ස්ථානයට තබන්න.",
            hintLevel2: "ඉලක්කම් විශාලත්වයේ සිට කුඩාත්වයට අනුපිළිවෙලින් තබන්න: 6, 4, 3, 1.",
            workedSolution: "6 > 4 > 3 > 1 අනුපිළිවෙලින් තැබූ විට විශාලතම සංඛ්‍යාව 6431 වේ.",
            skillTag: "four_digit_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c1_q4",
            conceptId: "c1_jungle_map",
            interactionType: "multipleChoice",
            questionText: "997 නිවැරදිව කියවන ආකාරය කුමක්ද?",
            options: ["නවසිය හතළිස් හත", "නවදහස් හත", "නවසිය අනූ හත", "අනූ නවසිය හත"],
            correctAnswer: "නවසිය අනූ හත",
            hintLevel1: "900 = නවසිය, 90 = අනූ, 7 = හත.",
            hintLevel2: "900 + 90 + 7 = 997.",
            workedSolution: "900 (නවසිය) + 90 (අනූ) + 7 (හත) = නවසිය අනූ හත.",
            skillTag: "number_name",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c1_q5",
            conceptId: "c1_jungle_map",
            interactionType: "digitBuilder",
            questionText: "4, 9, 0, 5 ඉලක්කම් භාවිතයෙන් 4905 සංඛ්‍යාව සාදන්න.",
            correctAnswer: "4905",
            options: ["4905", "4950", "4095", "9405"],
            hintLevel1: "දහස්ස්ථානයට 4, සියයස්ථානයට 9, දහයස්ථානයට 0, ඒකස්ථානයට 5 තබන්න.",
            hintLevel2: "4 -> 9 -> 0 -> 5 අනුපිළිවෙලින් ඉලක්කම් අදින්න.",
            workedSolution: "4 (දහස්) + 9 (සිය) + 0 (දහය) + 5 (ඒක) = 4905.",
            skillTag: "four_digit_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c1_q6",
            conceptId: "c1_jungle_map",
            interactionType: "numericInput",
            questionText: "\"හත්දහස් හාරසිය තිස් එක\" ඉලක්කම් වලින් ලියන්න.",
            correctAnswer: "7431",
            hintLevel1: "හත්දහස් = 7000, හාරසිය = 400, තිස් එක = 31.",
            hintLevel2: "7000 + 400 + 30 + 1 = 7431.",
            workedSolution: "7000 (හත්දහස්) + 400 (හාරසිය) + 31 (තිස් එක) = 7431.",
            skillTag: "four_digit_number",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 2: RIVER OF BEADS — 4-digit Place Value & Abacus ───
      {
        id: "c2_river_of_beads",
        conceptId: "c2_river_of_beads",
        title: "සංකල්පය 2: පබළු ගඟ",
        subtitle: "ඉලක්කම් 4ක සංඛ්‍යාවල ස්ථානීය අගය",
        learningObjective: "ඉලක්කම් 4ක සංඛ්‍යාවල ස්ථානීය අගය (ඒකස්ථානය, දහස්ථානය, සියස්ථානය, දහස්ස්ථානය)",
        orderIndex: 2,
        questions: [
          {
            id: "c2_q1",
            conceptId: "c2_river_of_beads",
            interactionType: "placeValuePicker",
            questionText: "5,421 සංඛ්‍යාවේ '1' ඉලක්කම පිහිටා ඇති ස්ථානීය අගය තෝරන්න.",
            options: ["දහයස්ථානය", "සියයස්ථානය", "ඒකස්ථානය", "දහසස්ථානය"],
            correctAnswer: "ඒකස්ථානය",
            hintLevel1: "දකුණුපසම ඇති පළමු ඉලක්කම නිරූපණය කරන්නේ ඒකස්ථානයයි.",
            hintLevel2: "5,421 හි දකුණුපසම 1 ඇත. එම නිසා එය ඒකස්ථානය වේ.",
            workedSolution: "සංඛ්‍යාවක දකුණුපසම ඇති ඉලක්කම ඒකස්ථානයයි (1).",
            skillTag: "place_value_units",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c2_q2",
            conceptId: "c2_river_of_beads",
            interactionType: "abacusChallenge",
            questionText: "3,618 සංඛ්‍යාව පබළු භාවිතයෙන් ගණක රාමුවේ නිරූපණය කරන්න.",
            correctAnswer: "3618",
            options: ["3618", "3168", "6318", "3681"],
            hintLevel1: "දහස්ස්ථානයට 3ක්, සියයස්ථානයට 6ක්, දහයස්ථානයට 1ක්, ඒකස්ථානයට 8ක් එකතු කරන්න.",
            hintLevel2: "3000 + 600 + 10 + 8 = 3618.",
            workedSolution: "දහස් (3), සිය (6), දහය (1), ඒක (8) ගණක රාමුවේ තැබූ විට 3618 වේ.",
            skillTag: "place_value_thousands",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c2_q3",
            conceptId: "c2_river_of_beads",
            interactionType: "abacusChallenge",
            questionText: "5,421 සංඛ්‍යාව පබළු භාවිතයෙන් ගණක රාමුවේ නිරූපණය කරන්න.",
            correctAnswer: "5421",
            options: ["5421", "5241", "4521", "5412"],
            hintLevel1: "දහස් (5), සිය (4), දහය (2), ඒක (1) කණුවල පබළු තබන්න.",
            hintLevel2: "5000 + 400 + 20 + 1 = 5421.",
            workedSolution: "5000 + 400 + 20 + 1 = 5421.",
            skillTag: "place_value_thousands",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c2_q4",
            conceptId: "c2_river_of_beads",
            interactionType: "placeValuePicker",
            questionText: "5,421 හි '4' ඉලක්කම තිබෙන ස්ථානය කුමක්ද?",
            options: ["දහසස්ථානය", "සියයස්ථානය", "දහයස්ථානය", "ඒකස්ථානය"],
            correctAnswer: "සියයස්ථානය",
            hintLevel1: "දකුණේ සිට බලන විට: 1 (ඒක), 2 (දහය), 4 (සියය).",
            hintLevel2: "4 පිහිටා ඇත්තේ තෙවන ස්ථානයේ එනම් සියයස්ථානයේය.",
            workedSolution: "5,421 හි 4 තිබෙන්නේ තෙවන ස්ථානයේය (සියයස්ථානය).",
            skillTag: "place_value_hundreds",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c2_q5",
            conceptId: "c2_river_of_beads",
            interactionType: "numericInput",
            questionText: "5,421 හි '4' ඉලක්කමෙන් නිරූපිත අගය ලියන්න.",
            correctAnswer: "400",
            hintLevel1: "4 තිබෙන්නේ සියයස්ථානයේය. 4 × 100 ගණනය කරන්න.",
            hintLevel2: "සියයස්ථානයේ ඇති 4 හි අගය 400 කි.",
            workedSolution: "4 සියයස්ථානයේ ඇති බැවින් 4 × 100 = 400 වේ.",
            skillTag: "digit_value",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c2_q6",
            conceptId: "c2_river_of_beads",
            interactionType: "multipleChoice",
            questionText: "4,905 හි දහයස්ථානයේ ඇති '0' ඉලක්කමේ නිරූපිත අගය කොපමණද?",
            options: ["10", "100", "40", "0"],
            correctAnswer: "0",
            hintLevel1: "0 ඕනෑම ස්ථානයක තිබුණද එහි නිරූපිත අගය 0ම වේ.",
            hintLevel2: "0 × 10 = 0 වේ.",
            workedSolution: "0 ඉලක්කම දහයස්ථානයේ තිබුණද 0 × 10 = 0 අගයක් නිරූපණය කරයි.",
            skillTag: "digit_value",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 3: GIANT'S GATE — Numbers up to 100,000 ───
      {
        id: "c3_giants_gate",
        conceptId: "c3_giants_gate",
        title: "සංකල්පය 3: යෝධ දොරටුව",
        subtitle: "100,000 දක්වා සංඛ්‍යා",
        learningObjective: "100,000 දක්වා සංඛ්‍යා කියවීම, ලිවීම සහ සංඛ්‍යා නාම",
        orderIndex: 3,
        questions: [
          {
            id: "c3_q1",
            conceptId: "c3_giants_gate",
            interactionType: "multipleChoice",
            questionText: "\"දහදහස් එකසිය\" ඉලක්කම් වලින් ලියූ විට කුමක්ද?",
            options: ["10,010", "1,010", "10,100", "100,100"],
            correctAnswer: "10,100",
            hintLevel1: "දහදහස් = 10,000, එකසිය = 100.",
            hintLevel2: "10,000 + 100 = 10,100.",
            workedSolution: "10,000 + 100 = 10,100.",
            skillTag: "five_digit_number",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c3_q2",
            conceptId: "c3_giants_gate",
            interactionType: "numericInput",
            questionText: "\"තිස්අටදහස් දහහත\" ඉලක්කම් වලින් ලියන්න.",
            correctAnswer: "38017",
            hintLevel1: "තිස්අටදහස් = 38,000. සියයස්ථානයේ කිසිවක් නැත (0). දහහත = 17.",
            hintLevel2: "38,000 + 0 + 17 = 38017.",
            workedSolution: "38,000 (තිස්අටදහස්) + 0 (සියය) + 17 (දහහත) = 38017.",
            skillTag: "five_digit_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c3_q3",
            conceptId: "c3_giants_gate",
            interactionType: "digitBuilder",
            questionText: "7, 5, 5, 0, 1 ඉලක්කම් භාවිතයෙන් 75501 සංඛ්‍යාව සාදන්න.",
            correctAnswer: "75501",
            options: ["75501", "75051", "57501", "75510"],
            hintLevel1: "75,000 (දසදහස් 7, දහස් 5) + 500 (සිය 5) + 0 + 1.",
            hintLevel2: "7 -> 5 -> 5 -> 0 -> 1 අනුපිළිවෙලින් තබන්න.",
            workedSolution: "75,501 හි ඉලක්කම් අනුපිළිවෙල 75501 වේ.",
            skillTag: "five_digit_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c3_q4",
            conceptId: "c3_giants_gate",
            interactionType: "multipleChoice",
            questionText: "25,602 සංඛ්‍යාවේ සංඛ්‍යා නාමය කුමක්ද?",
            options: [
              "විසිපන්දහස් හයසිය විස්ස",
              "දෙදහස් පන්සිය හටදෙක",
              "විසිපන්දහස් හයසිය දෙක",
              "විසිපන්දහස් විස්ස",
            ],
            correctAnswer: "විසිපන්දහස් හයසිය දෙක",
            hintLevel1: "25,000 = විසිපන්දහස්, 600 = හයසිය, 2 = දෙක.",
            hintLevel2: "25,000 + 600 + 2 = විසිපන්දහස් හයසිය දෙක.",
            workedSolution: "25,000 (විසිපන්දහස්) + 600 (හයසිය) + 2 (දෙක) = විසිපන්දහස් හයසිය දෙක.",
            skillTag: "number_name",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c3_q5",
            conceptId: "c3_giants_gate",
            interactionType: "digitBuilder",
            questionText: "5, 3, 9, 0, 0 ඉලක්කම් භාවිතයෙන් 53900 සංඛ්‍යාව සාදන්න.",
            correctAnswer: "53900",
            options: ["53900", "53090", "59300", "35900"],
            hintLevel1: "5 (දසදහස්) + 3 (දහස්) + 9 (සිය) + 0 + 0.",
            hintLevel2: "5 -> 3 -> 9 -> 0 -> 0 අනුපිළිවෙලින් තබන්න.",
            workedSolution: "53,900 හි ඉලක්කම් 53900 වේ.",
            skillTag: "five_digit_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c3_q6",
            conceptId: "c3_giants_gate",
            interactionType: "multipleChoice",
            questionText: "\"සියක් දහස\" ලියනු ලබන්නේ කුමන ඉලක්කම් වලින්ද?",
            options: ["10,000", "1,000,000", "99,999", "100,000"],
            correctAnswer: "100,000",
            hintLevel1: "සියයක් (100) × දහසක් (1000).",
            hintLevel2: "100 ළඟට බිංදු 3ක් එක් කළ විට 100,000 වේ.",
            workedSolution: "සියක් දහස (100 × 1,000) යනු 100,000 වේ.",
            skillTag: "five_digit_number",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 4: GLOWING PEDESTALS — Ten-thousands place ───
      {
        id: "c4_glowing_pedestals",
        conceptId: "c4_glowing_pedestals",
        title: "සංකල්පය 4: දිදුලන පීඨය",
        subtitle: "දස දහස් ස්ථානය",
        learningObjective: "පස්ස්ථානීය සංඛ්‍යාවල දස දහස්ස්ථානයේ අගය හඳුනාගැනීම",
        orderIndex: 4,
        questions: [
          {
            id: "c4_q1",
            conceptId: "c4_glowing_pedestals",
            interactionType: "placeValuePicker",
            questionText: "68,507 හි '6' ඉලක්කම පිහිටා ඇති ස්ථානීය අගය කුමක්ද?",
            options: ["දහසස්ථානය", "දස දහසස්ථානය", "සියයස්ථානය", "දහයස්ථානය"],
            correctAnswer: "දස දහසස්ථානය",
            hintLevel1: "පස්වන ස්ථානය (වම්පසම ඉලක්කම) දස දහසස්ථානයයි.",
            hintLevel2: "68,507 හි 6 ඇත්තේ 5 වන ස්ථානය හෙවත් දස දහසස්ථානයේය.",
            workedSolution: "ඉලක්කම් 5ක සංඛ්‍යාවක 5 වන ස්ථානය දස දහසස්ථානය වේ.",
            skillTag: "ten_thousands_place",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c4_q2",
            conceptId: "c4_glowing_pedestals",
            interactionType: "placeValuePicker",
            questionText: "68,507 හි '6' ඉලක්කමෙන් නිරූපණය වන අගය කුමක්ද?",
            options: ["6,000", "600", "60,000", "60"],
            correctAnswer: "60,000",
            hintLevel1: "6 තිබෙන්නේ දස දහසස්ථානයේය. 6 × 10,000 ගණනය කරන්න.",
            hintLevel2: "6 × 10,000 = 60,000.",
            workedSolution: "6 දස දහසස්ථානයේ පිහිටි බැවින් එහි නිරූපිත අගය 60,000 වේ.",
            skillTag: "digit_value",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c4_q3",
            conceptId: "c4_glowing_pedestals",
            interactionType: "numericInput",
            questionText: "35,421 හි '3' ඉලක්කමේ නිරූපිත අගය ලියන්න.",
            correctAnswer: "30000",
            hintLevel1: "3 ඇත්තේ දස දහසස්ථානයේය. 3 × 10,000 කරන්න.",
            hintLevel2: "3 × 10,000 = 30,000.",
            workedSolution: "3 × 10,000 = 30,000 වේ.",
            skillTag: "ten_thousands_place",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c4_q4",
            conceptId: "c4_glowing_pedestals",
            interactionType: "placeValuePicker",
            questionText: "26,147 හි '2' පිහිටා ඇත්තේ දස දහසස්ථානයේය. එහි අගය කුමක්ද?",
            options: ["2,000", "200", "20,000", "20"],
            correctAnswer: "20,000",
            hintLevel1: "දස දහස් 2ක් යනු කොපමණද?",
            hintLevel2: "2 × 10,000 = 20,000.",
            workedSolution: "2 × 10,000 = 20,000 වේ.",
            skillTag: "digit_value",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c4_q5",
            conceptId: "c4_glowing_pedestals",
            interactionType: "multipleChoice",
            questionText: "68,507 හි සියයස්ථානයේ ඇති '5' ඉලක්කමේ නිරූපිත අගය කොපමණද?",
            options: ["5,000", "500", "50", "5"],
            correctAnswer: "500",
            hintLevel1: "5 තිබෙන්නේ සියයස්ථානයේය. 5 × 100 බලන්න.",
            hintLevel2: "5 × 100 = 500.",
            workedSolution: "5 සියයස්ථානයේ පිහිටි බැවින් එහි නිරූපිත අගය 500 වේ.",
            skillTag: "digit_value",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c4_q6",
            conceptId: "c4_glowing_pedestals",
            interactionType: "multipleChoice",
            questionText: "68,507 හි දහයස්ථානයේ ඇති '0' ඉලක්කමේ නිරූපිත අගය කොපමණද?",
            options: ["10", "500", "0", "60000"],
            correctAnswer: "0",
            hintLevel1: "0 ඉලක්කම දහයස්ථානයේ තිබුණද එහි අගය 0 වේ.",
            hintLevel2: "0 × 10 = 0.",
            workedSolution: "0 × 10 = 0 වේ.",
            skillTag: "ten_thousands_place",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 5: UNLOCKING THE CHEST — Expanded form ───
      {
        id: "c5_unlocking_chest",
        conceptId: "c5_unlocking_chest",
        title: "සංකල්පය 5: රන් අඹ පෙට්ටිය",
        subtitle: "විහිදුවා ලිවීම (Expanded Form)",
        learningObjective: "සංඛ්‍යාවක් ස්ථානීය අගයන්ගේ එකතුවක් ලෙස විහිදුවා ලිවීම",
        orderIndex: 5,
        questions: [
          {
            id: "c5_q1",
            conceptId: "c5_unlocking_chest",
            interactionType: "multipleChoice",
            questionText: "6,831 විහිදුවා ලියන නිවැරදි ආකාරය තෝරන්න.",
            options: [
              "600 + 800 + 30 + 1",
              "6000 + 80 + 300 + 1",
              "60000 + 800 + 30 + 1",
              "6000 + 800 + 30 + 1",
            ],
            correctAnswer: "6000 + 800 + 30 + 1",
            hintLevel1: "6000 (දහස්) + 800 (සිය) + 30 (දහය) + 1 (ඒක).",
            hintLevel2: "ස්ථානීය අගයන් එකතු කරන්න: 6000 + 800 + 30 + 1.",
            workedSolution: "6,831 = 6000 + 800 + 30 + 1 වේ.",
            skillTag: "expanded_form",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c5_q2",
            conceptId: "c5_unlocking_chest",
            interactionType: "expandedForm",
            questionText: "68,507 විහිදුවා ලියූ කොටස් නිවැරදිව පේළියට තබන්න.",
            correctAnswer: "60000 + 8000 + 500 + 0 + 7",
            options: [
              "60000 + 8000 + 500 + 0 + 7",
              "6000 + 800 + 50 + 0 + 7",
              "60000 + 800 + 500 + 7",
              "60000 + 8000 + 50 + 7",
            ],
            hintLevel1: "60,000 + 8,000 + 500 + 0 + 7.",
            hintLevel2: "දසදහස් 6 = 60,000, දහස් 8 = 8,000, සිය 5 = 500, දහය = 0, ඒක = 7.",
            workedSolution: "68,507 = 60,000 + 8,000 + 500 + 0 + 7 වේ.",
            skillTag: "expanded_form",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c5_q3",
            conceptId: "c5_unlocking_chest",
            interactionType: "expandedForm",
            questionText: "45,600 විහිදුවා ලියූ කොටස් නිවැරදිව පේළියට තබන්න.",
            correctAnswer: "40000 + 5000 + 600 + 0 + 0",
            options: [
              "40000 + 5000 + 600 + 0 + 0",
              "4000 + 500 + 60 + 0",
              "40000 + 500 + 600",
              "40000 + 5000 + 60",
            ],
            hintLevel1: "40,000 (දසදහස් 4) + 5,000 (දහස් 5) + 600 (සිය 6) + 0 + 0.",
            hintLevel2: "40000 + 5000 + 600 + 0 + 0.",
            workedSolution: "45,600 = 40000 + 5000 + 600 + 0 + 0 වේ.",
            skillTag: "expanded_form",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c5_q4",
            conceptId: "c5_unlocking_chest",
            interactionType: "numericInput",
            questionText: "68,507 = 60,000 + ? + 500 + 0 + 7 හි හිස්තැනට සුදුසු අගය ලියන්න.",
            correctAnswer: "8000",
            hintLevel1: "8 තිබෙන්නේ දහසස්ථානයේය. 8 × 1000 සිතන්න.",
            hintLevel2: "දහසස්ථානයේ ඇති 8 හි අගය 8,000 කි.",
            workedSolution: "68,507 හි 8 ඇත්තේ දහසස්ථානයේ බැවින් එහි අගය 8,000 වේ.",
            skillTag: "expanded_form",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c5_q5",
            conceptId: "c5_unlocking_chest",
            interactionType: "multipleChoice",
            questionText: "68,507 හි දහයස්ථානයේ විහිදුවූ අගය 0 වේ. මන්ද?",
            options: [
              "දහයස්ථානයේ ඇති ඉලක්කම 0 නිසා",
              "දහයස්ථානයක් නැති නිසා",
              "දහයස්ථානයේ අගය 100 නිසා",
              "සංඛ්‍යාව කුඩා නිසා",
            ],
            correctAnswer: "දහයස්ථානයේ ඇති ඉලක්කම 0 නිසා",
            hintLevel1: "0 ඉලක්කම ඕනෑම ස්ථානයක තිබුණද එහි අගය 0 වේ.",
            hintLevel2: "0 × 10 = 0 වේ.",
            workedSolution: "දහයස්ථානයේ 0 ඇති බැවින් එහි විහිදුවූ අගය 0 × 10 = 0 වේ.",
            skillTag: "expanded_form_zero",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c5_q6",
            conceptId: "c5_unlocking_chest",
            interactionType: "multipleChoice",
            questionText: "90,000 + 0 + 900 + 90 + 9 විහිදුවූ අගයන්ගෙන් සෑදෙන සංඛ්‍යාව කුමක්ද?",
            options: ["99,999", "90,999", "90,990", "9,999"],
            correctAnswer: "90,999",
            hintLevel1: "දහස්ස්ථානයේ අගය 0 වේ! 90,000 + 0 + 999 සිතන්න.",
            hintLevel2: "90,000 + 999 = 90,999.",
            workedSolution: "දහස්ස්ථානයේ 0 ඇති බැවින් සංඛ්‍යාව 90,999 වේ.",
            skillTag: "expanded_form_zero",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },
    ],
  },

  // ─── LESSON 2: THE GREAT NUMBER TRAIN (Comparing & Ordering) ───────────────
  {
    id: "lesson_2_number_train",
    title: "පාඩම 2: මහා සංඛ්‍යා දුම්රිය (Comparing & Ordering Numbers)",
    lessonNumber: 2,
    description: "සංඛ්‍යා සංසන්දනය, ආරෝහණ හා අවරෝහණ පිළිවෙළ, ඉලක්කම් පත් භාවිතයෙන් සංඛ්‍යා නිර්මාණය සහ දහස් කඳුකරය",
    conceptId: "number_train_adventure",
    status: "published",
    grade: 5,
    concepts: [
      // ─── CONCEPT 1: NUMBER TRAIN STATION — Comparing numbers ───
      {
        id: "c1_number_train_station",
        conceptId: "c1_number_train_station",
        title: "සංකල්පය 1: පළමු නැවතුම – සංඛ්‍යා සසඳමු",
        subtitle: "විශාලම සහ කුඩාම සංඛ්‍යාව සොයමු",
        learningObjective: "සංඛ්‍යා 3ක් අතරින් විශාලම සහ කුඩාම සංඛ්‍යාව හඳුනාගැනීම සහ පෙළගැස්වීම",
        orderIndex: 1,
        questions: [
          {
            id: "c1_ch1",
            conceptId: "c1_number_train_station",
            interactionType: "multipleChoice",
            questionText: "56, 28, 32 අතරින් විශාලම සංඛ්‍යාව තෝරන්න.",
            options: ["56", "28", "32"],
            correctAnswer: "56",
            hintLevel1: "මුලින්ම දහයස්ථානයේ ඉලක්කම් බලමු. 5, 2, 3 අතරින් විශාලම ඉලක්කම කුමක්ද?",
            hintLevel2: "56 හි දහයස්ථානයේ 5ක් තියෙනවා. 28 හි 2ක් සහ 32 හි 3ක් තියෙනවා. එබැවින් විශාලම සංඛ්‍යාව කුමක්ද?",
            workedSolution: "දහයස්ථානයේ ඉලක්කම විශාල වන විට, මේ සංඛ්‍යා අතර එය විශාල සංඛ්‍යාව වේ. 5 > 3 > 2 නිසා 56 විශාලම සංඛ්‍යාවයි.",
            skillTag: "compare_two_digit_numbers",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c1_ch2",
            conceptId: "c1_number_train_station",
            interactionType: "multipleChoice",
            questionText: "විශාලම සංඛ්‍යාව සහිත ටිකට්පත දුම්රිය ටිකට් කවුන්ටරයට ඇද තබන්න.",
            options: ["541", "358", "722"],
            correctAnswer: "722",
            hintLevel1: "සියයස්ථානයේ ඉලක්කම් බලමු: 5, 3, 7 අතරින් විශාලම ඉලක්කම කුමක්ද?",
            hintLevel2: "722 හි සියයස්ථානයේ 7ක් ඇත. එය 5 සහ 3ට වඩා විශාලය.",
            workedSolution: "සියයස්ථානයේ 7 > 5 > 3 බැවින් විශාලම සංඛ්‍යාව 722 වේ.",
            skillTag: "compare_three_digit_numbers",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c1_ch3",
            conceptId: "c1_number_train_station",
            interactionType: "multipleChoice",
            questionText: "කුඩාම සංඛ්‍යාවේ සිට විශාලම සංඛ්‍යාව දක්වා දුම්රිය මැදිරි සකස් කරන්න.",
            options: ["28, 32, 56", "56, 32, 28", "32, 28, 56", "28, 56, 32"],
            correctAnswer: "28, 32, 56",
            hintLevel1: "දහයස්ථානයේ ඉලක්කම් කුඩාම සංඛ්‍යාවේ සිට පෙළගස්වන්න: 2, 3, 5.",
            hintLevel2: "28 (දහය 2) ➔ 32 (දහය 3) ➔ 56 (දහය 5) අනුපිළිවෙල සිතන්න.",
            workedSolution: "දහයස්ථාන අගයන් සසඳන විට: 28 < 32 < 56 වේ.",
            skillTag: "ascending_order",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c1_ch4",
            conceptId: "c1_number_train_station",
            interactionType: "multipleChoice",
            questionText: "541, 528, 301 අතරින් විශාලම සංඛ්‍යාව සොයන්න.",
            options: ["541", "528", "301"],
            correctAnswer: "541",
            hintLevel1: "සියයස්ථානයේ 541 සහ 528 දෙකෙහිම 5 ඇත. එනිසා දහයස්ථානය බලන්න.",
            hintLevel2: "541 හි දහයස්ථානයේ 4ක් ද, 528 හි 2ක් ද ඇත. 4 > 2 වේ.",
            workedSolution: "සියයස්ථාන සමාන නිසා දහයස්ථානය සසඳමු: 4 > 2 බැවින් 541 > 528 > 301 වේ.",
            skillTag: "place_value_comparison",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c1_ch5",
            conceptId: "c1_number_train_station",
            interactionType: "multipleChoice",
            questionText: "කුඩාම සංඛ්‍යාවේ සිට විශාලම සංඛ්‍යාව දක්වා දුම්රිය මැදිරි පේළිගත කරන්න.",
            options: ["219, 258, 352", "352, 258, 219", "258, 219, 352", "219, 352, 258"],
            correctAnswer: "219, 258, 352",
            hintLevel1: "සියයස්ථානය බලන්න: 219 සහ 258 හි සියයස්ථානයේ 2 ඇත. දහයස්ථානයේ 1 < 5 වේ.",
            hintLevel2: "කුඩාම සංඛ්‍යාව 219 වේ. ඉන්පසු 258 සහ විශාලම සංඛ්‍යාව 352 වේ.",
            workedSolution: "සියයස්ථාන සහ දහයස්ථාන අනුපිළිවෙලින්: 219 < 258 < 352 වේ.",
            skillTag: "number_ordering",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c1_ch6",
            conceptId: "c1_number_train_station",
            interactionType: "multipleChoice",
            questionText: "මෙම සංඛ්‍යා තුන කුඩාම සංඛ්‍යාවේ සිට විශාලම සංඛ්‍යාව දක්වා පටිපාටිගත කරන්න.",
            options: ["3967, 4512, 4825", "4825, 4512, 3967", "3967, 4825, 4512", "4512, 3967, 4825"],
            correctAnswer: "3967, 4512, 4825",
            hintLevel1: "දහස්ස්ථානය බලන්න: 3,967 හි දහස්ස්ථානයේ 3 ඇත. එය කුඩාම වේ!",
            hintLevel2: "4,825 සහ 4,512 හි දහස් 4 බැවින් සියයස්ථානය බලන්න: 500 < 800 වේ.",
            workedSolution: "දහස්ස්ථානයෙන් 3,967 කුඩාම වේ. සියයස්ථානයෙන් 4,512 < 4,825 වේ. අනුපිළිවෙල: 3,967 ➔ 4,512 ➔ 4,825.",
            skillTag: "compare_four_digit_numbers",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 2: ORDERING — Ascending & Descending ───
      {
        id: "c2_number_train_ordering",
        conceptId: "c2_number_train_ordering",
        title: "සංකල්පය 2: දෙවන නැවතුම – සංඛ්‍යා පටිපාටිගත කරමු",
        subtitle: "ආරෝහණ හා අවරෝහණ පිළිවෙළ",
        learningObjective: "සංඛ්‍යා තුනක් ආරෝහණ හා අවරෝහණ පිළිවෙළට පටිපාටිගත කිරීම",
        orderIndex: 2,
        questions: [
          {
            id: "c2_ch1",
            conceptId: "c2_number_train_ordering",
            interactionType: "multipleChoice",
            questionText: "45, 18, 62 අතරින් කුඩාම සංඛ්‍යාව තෝරන්න.",
            options: ["45", "18", "62"],
            correctAnswer: "18",
            hintLevel1: "දහයස්ථානයේ ඉලක්කම් බලන්න: 4, 1, 6. කුඩාම දහය කුමක්ද?",
            hintLevel2: "18 හි දහයස්ථානයේ 1 ඇත. එය 4 සහ 6 ට වඩා කුඩාය.",
            workedSolution: "දහයස්ථානය සසඳන විට: 1 < 4 < 6 බැවින් 18 කුඩාම සංඛ්‍යාව වේ.",
            skillTag: "smallest_number",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c2_ch2",
            conceptId: "c2_number_train_ordering",
            interactionType: "multipleChoice",
            questionText: "සංඛ්‍යා කුඩාම සංඛ්‍යාවේ සිට විශාලම සංඛ්‍යාව දක්වා (ආරෝහණ පිළිවෙළට) සකස් කරන්න.",
            options: ["47, 74, 81", "81, 74, 47", "74, 47, 81", "47, 81, 74"],
            correctAnswer: "47, 74, 81",
            hintLevel1: "දහයස්ථානයේ ඉලක්කම් බලන්න: 7, 4, 8. කුඩාම ඉලක්කම පළමුවට තබන්න.",
            hintLevel2: "47 (දහය 4) ➔ 74 (දහය 7) ➔ 81 (දහය 8) ලෙස පටිපාටිගත කරන්න.",
            workedSolution: "දහයස්ථානයෙන්: 4 < 7 < 8 බැවින් ආරෝහණ පිළිවෙළ 47 ➔ 74 ➔ 81 වේ.",
            skillTag: "ascending_order",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c2_ch3",
            conceptId: "c2_number_train_ordering",
            interactionType: "multipleChoice",
            questionText: "විශාලම සංඛ්‍යාවේ සිට කුඩාම සංඛ්‍යාව දක්වා (අවරෝහණ පිළිවෙළට) සකස් කරන්න.",
            options: ["95, 88, 63", "63, 88, 95", "88, 95, 63", "95, 63, 88"],
            correctAnswer: "95, 88, 63",
            hintLevel1: "අවරෝහණ පිළිවෙළ යනු විශාලම සිට කුඩාම දක්වාය. විශාලම සංඛ්‍යාව පළමුවට තබන්න.",
            hintLevel2: "95 (දහය 9) ➔ 88 (දහය 8) ➔ 63 (දහය 6) ලෙස අවරෝහණ පිළිවෙළට සකස් කරන්න.",
            workedSolution: "දහයස්ථානයෙන්: 9 > 8 > 6 බැවින් අවරෝහණ පිළිවෙළ 95 ➔ 88 ➔ 63 වේ.",
            skillTag: "descending_order",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c2_ch4",
            conceptId: "c2_number_train_ordering",
            interactionType: "multipleChoice",
            questionText: "මෙම සංඛ්‍යා ආරෝහණ පිළිවෙළට පෙළගස්වන්න.",
            options: ["412, 450, 489", "489, 450, 412", "412, 489, 450", "450, 412, 489"],
            correctAnswer: "412, 450, 489",
            hintLevel1: "සියලුම සංඛ්‍යාවල සියයස්ථානයේ 4 ඇත. එබැවින් දහයස්ථානය සසඳන්න.",
            hintLevel2: "දහයස්ථානයේ 1, 8, 5 ඇත. ඒවා කුඩාම සිට විශාලමට පෙළගස්වන්න.",
            workedSolution: "සියයස්ථාන සමාන නිසා දහයස්ථානය සසඳමු: 1 < 5 < 8 බැවින් පිළිවෙළ 412 ➔ 450 ➔ 489 වේ.",
            skillTag: "guided_ascending_comparison",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c2_ch5",
            conceptId: "c2_number_train_ordering",
            interactionType: "multipleChoice",
            questionText: "කුඩාම සංඛ්‍යාවේ සිට විශාලම සංඛ්‍යාව දක්වා දුම්රිය මැදිරි සකස් කරන්න.",
            options: ["621, 799, 805", "805, 799, 621", "621, 805, 799", "799, 621, 805"],
            correctAnswer: "621, 799, 805",
            hintLevel1: "සියයස්ථානය බලන්න: 8, 6, 7. කුඩාම සියයස්ථානය කුමක්ද?",
            hintLevel2: "621 (සියය 6) පළමුවත්, 799 (සියය 7) දෙවනුවත් පැමිණේ.",
            workedSolution: "සියයස්ථාන සසඳන විට: 6 < 7 < 8 බැවින් ආරෝහණ පිළිවෙළ 621 ➔ 799 ➔ 805 වේ.",
            skillTag: "ascending_order_3digit",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c2_ch6",
            conceptId: "c2_number_train_ordering",
            interactionType: "multipleChoice",
            questionText: "මෙම සංඛ්‍යා තුන අවරෝහණ පිළිවෙළට (විශාලම සිට කුඩාමට) සකස් කරන්න.",
            options: ["5610, 5240, 2980", "2980, 5240, 5610", "5240, 5610, 2980", "5610, 2980, 5240"],
            correctAnswer: "5610, 5240, 2980",
            hintLevel1: "දහස්ස්ථානය බලන්න: 5, 2, 5. විශාලම දහස්ස්ථානය 5 වේ.",
            hintLevel2: "5,610 සහ 5,240 හි දහස් 5 බැවින් සියයස්ථානය බලන්න: 600 > 200 වේ.",
            workedSolution: "දහස්ස්ථානයෙන් 5 > 2 වේ. 5,610 සහ 5,240 හි සියයස්ථානය සසඳන විට 6 > 2 වේ. අනුපිළිවෙළ: 5,610 ➔ 5,240 ➔ 2,980.",
            skillTag: "descending_order_4digit",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 3: DIGIT CARD TRAIN — Building numbers with digit cards ───
      {
        id: "c3_digit_card_train",
        conceptId: "c3_digit_card_train",
        title: "සංකල්පය 3: තෙවන නැවතුම – ඉලක්කම් පත්‍ර දුම්රිය",
        subtitle: "ඉලක්කම් පත්වලින් සංඛ්‍යා හදමු",
        learningObjective: "0-9 ඉලක්කම් පත් භාවිත කර සංඛ්‍යා නිර්මාණය සහ සංසන්දනය",
        orderIndex: 3,
        questions: [
          {
            id: "c3_ch1",
            conceptId: "c3_digit_card_train",
            interactionType: "digitBuilder",
            questionText: "මෙම ඉලක්කම් භාවිත කර 6431 සංඛ්‍යාව සාදන්න.",
            correctAnswer: "6431",
            options: ["6431", "6341", "4631", "6413"],
            hintLevel1: "ඉලක්කම් හතර නිවැරදි ස්ථානවලට තබන්න.",
            hintLevel2: "හදන්න ඕනේ 6431. මුලින් 6 තබන්න.",
            workedSolution: "6 දහස්ස්ථානයේ, 4 සියයස්ථානයේ, 3 දහයස්ථානයේ සහ 1 ඒකස්ථානයේ ඇත.",
            skillTag: "digit_construction",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c3_ch2",
            conceptId: "c3_digit_card_train",
            interactionType: "digitBuilder",
            questionText: "දුම්රිය මැදිරියේ අංකය 5,284 විය යුතුයි. ඉලක්කම් පත් නිවැරදි අනුපිළිවෙළට තබන්න.",
            correctAnswer: "5284",
            options: ["5284", "5824", "5482", "5248"],
            hintLevel1: "මුලින්ම දහස්ස්ථානය ගැන සිතන්න.",
            hintLevel2: "5 ➔ 2 ➔ 8 ➔ 4 ලෙස තබන්න.",
            workedSolution: "5 දහස් + 2 සිය + 8 දහය + 4 ඒක = 5284 වේ.",
            skillTag: "card_placement",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c3_ch3",
            conceptId: "c3_digit_card_train",
            interactionType: "digitBuilder",
            questionText: "මෙම ඉලක්කම් හතරෙන් (3, 8, 1, 6) සෑදිය හැකි විශාලම සංඛ්‍යාව සාදන්න.",
            correctAnswer: "8631",
            options: ["8631", "8613", "8361", "6831"],
            hintLevel1: "විශාලම ඉලක්කම මුලට තබන්න.",
            hintLevel2: "8 පළමුවත්, ඉන් පසු 6, 3, 1ත් තබන්න.",
            workedSolution: "විශාලම සංඛ්‍යාව සෑදීමට ඉලක්කම් විශාලතම එකේ සිට කුඩාම එක දක්වා තැබිය හැක (8631).",
            skillTag: "make_largest_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c3_ch4",
            conceptId: "c3_digit_card_train",
            interactionType: "digitBuilder",
            questionText: "මෙම ඉලක්කම් හතරෙන් (7, 2, 9, 4) සෑදිය හැකි කුඩාම සංඛ්‍යාව සාදන්න.",
            correctAnswer: "2479",
            options: ["2479", "2497", "2749", "4279"],
            hintLevel1: "කුඩාම ඉලක්කම මුලට තබන්න.",
            hintLevel2: "2 ➔ 4 ➔ 7 ➔ 9 ලෙස තැබීමෙන් කුඩාම සංඛ්‍යාව ලැබේ.",
            workedSolution: "කුඩාම සංඛ්‍යාව සෑදීමට ඉලක්කම් කුඩාම එකේ සිට විශාලම එක දක්වා තැබිය හැක (2479).",
            skillTag: "make_smallest_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c3_ch5",
            conceptId: "c3_digit_card_train",
            interactionType: "multipleChoice",
            questionText: "කුමන දුම්රිය මැදිරියේ අංකය විශාලද? (6842 vs 6482)",
            options: ["6842", "6482", "දෙකම සමානයි"],
            correctAnswer: "6842",
            hintLevel1: "මුලින්ම දහස්ස්ථානය බලන්න. දෙකෙහිම 6 ඇත.",
            hintLevel2: "දැන් සියයස්ථානය බලන්න: 8 > 4 වේ. එනිසා 6842 විශාල වේ.",
            workedSolution: "දහස්ස්ථාන 6=6 වේ. සියයස්ථානයේ 8 > 4 බැවින් 6842 > 6482 වේ.",
            skillTag: "compare_constructed_numbers",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c3_ch6",
            conceptId: "c3_digit_card_train",
            interactionType: "digitBuilder",
            questionText: "1, 4, 7, 2, 9 ඉලක්කම් භාවිත කර සෑදිය හැකි විශාලම ඉලක්කම් 5 සංඛ්‍යාව සාදන්න.",
            correctAnswer: "97421",
            options: ["97421", "97412", "97241", "79421"],
            hintLevel1: "ඉලක්කම් 5 විශාලම එකේ සිට කුඩාම එක දක්වා සකස් කරන්න.",
            hintLevel2: "9 ➔ 7 ➔ 4 ➔ 2 ➔ 1 අනුපිළිවෙලට තබන්න.",
            workedSolution: "97,421 යනු මෙම ඉලක්කම් 5න් සෑදිය හැකි විශාලම 5-digit සංඛ්‍යාවයි!",
            skillTag: "master_digit_builder",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 4: THOUSANDS MOUNTAIN — 4 & 5 digit comparison ───
      {
        id: "c4_thousands_mountain",
        conceptId: "c4_thousands_mountain",
        title: "සංකල්පය 4: හතරවන නැවතුම – දහස් කඳුකරය",
        subtitle: "4 සහ 5 ඉලක්කම් සංඛ්‍යා සසඳමු",
        learningObjective: "99,999 දක්වා 4 සහ 5 ඉලක්කම් සංඛ්‍යා සසඳමින් දසදහස්ස්ථානය හඳුනාගැනීම",
        orderIndex: 4,
        questions: [
          {
            id: "c4_ch1",
            conceptId: "c4_thousands_mountain",
            interactionType: "multipleChoice",
            questionText: "18,508, 33,240, 61,088 අතරින් විශාලම සංඛ්‍යාව සොයන්න.",
            options: ["18508", "33240", "61088"],
            correctAnswer: "61088",
            hintLevel1: "දසදහස්ස්ථානය බලන්න: 1, 3, 6.",
            hintLevel2: "1, 3, 6 අතරින් 6 විශාලමයි. ඒ නිසා 61,088 විශාලම වේ.",
            workedSolution: "දසදහස්ස්ථානයේ 6 > 3 > 1 බැවින් 61,088 විශාලම සංඛ්‍යාව වේ.",
            skillTag: "mountain_largest_number",
            difficulty: 1,
            xpReward: 10,
          },
          {
            id: "c4_ch2",
            conceptId: "c4_thousands_mountain",
            interactionType: "expandedForm",
            questionText: "33,240 හි විස්තරාත්මක සටහන සාදන්න: 30,000 + 3,000 + 200 + 40 + 0",
            options: [
              "30000 + 3000 + 200 + 40 + 0",
              "3000 + 300 + 20 + 4",
              "30000 + 200 + 40",
              "33000 + 240",
            ],
            correctAnswer: "30000 + 3000 + 200 + 40 + 0",
            hintLevel1: "සෑම ඉලක්කමකම ස්ථානීය අගය වෙන වෙනම බලන්න.",
            hintLevel2: "33,240 = 30,000 + 3,000 + 200 + 40 + 0",
            workedSolution: "33,240 = 30,000 (දසදහස්) + 3,000 (දහස්) + 200 (සිය) + 40 (දහය) + 0 (ඒක).",
            skillTag: "expanded_form_5digit",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c4_ch3",
            conceptId: "c4_thousands_mountain",
            interactionType: "multipleChoice",
            questionText: "මෙම සංඛ්‍යා තුන කුඩාම සිට විශාලම දක්වා (ආරෝහණ පිළිවෙළට) සකස් කරන්න.",
            options: ["42900, 45600, 48200", "48200, 45600, 42900", "45600, 42900, 48200"],
            correctAnswer: "42900, 45600, 48200",
            hintLevel1: "දසදහස්ස්ථානයේ ඉලක්කම් තුනේම 4යි.",
            hintLevel2: "දහස්ස්ථානය බලන්න: 2, 5, 8. 42,900 පළමුවට තබන්න.",
            workedSolution: "දසදහස්ස්ථාන සමාන නිසා දහස්ස්ථානයෙන්: 2 < 5 < 8 ➔ 42,900 < 45,600 < 48,200.",
            skillTag: "equal_ten_thousands_comparison",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c4_ch4",
            conceptId: "c4_thousands_mountain",
            interactionType: "multipleChoice",
            questionText: "76,405 හි 7 ඉලක්කමෙන් දැක්වෙන අගය කීයද?",
            options: ["70,000 (දසදහස්ස්ථානය)", "7,000 (දහස්ස්ථානය)", "700 (සියයස්ථානය)"],
            correctAnswer: "70,000 (දසදහස්ස්ථානය)",
            hintLevel1: "7 තිබෙන්නේ කුමන ස්ථානයේදැයි බලන්න.",
            hintLevel2: "7 තිබෙන්නේ දසදහස්ස්ථානයේය. එනිසා එහි අගය 70,000 වේ.",
            workedSolution: "76,405 හි 7 දසදහස්ස්ථානයේ පිහිටන බැවින් එහි අගය 70,000 වේ.",
            skillTag: "value_detector",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c4_ch5",
            conceptId: "c4_thousands_mountain",
            interactionType: "multipleChoice",
            questionText: "විශාලම සංඛ්‍යාවේ සිට කුඩාම සංඛ්‍යාව දක්වා (අවරෝහණ පිළිවෙළට) මැදිරි සකස් කරන්න.",
            options: ["76500, 54543, 14628", "14628, 54543, 76500", "54543, 76500, 14628"],
            correctAnswer: "76500, 54543, 14628",
            hintLevel1: "දසදහස්ස්ථානය බලන්න: 7, 5, 1.",
            hintLevel2: "7 > 5 > 1 නිසා 76,500 පළමුව, 54,543 දෙවනුව, 14,628 අවසානයේ.",
            workedSolution: "දසදහස්ස්ථානයෙන් 7 > 5 > 1 බැවින් අවරෝහණ පිළිවෙළ 76,500 ➔ 54,543 ➔ 14,628 වේ.",
            skillTag: "descending_mountain_sort",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c4_ch6",
            conceptId: "c4_thousands_mountain",
            interactionType: "multipleChoice",
            questionText: "මෙම සංඛ්‍යා 5 කුඩාම සිට විශාලම දක්වා (ආරෝහණ පිළිවෙළට) සකස් කරන්න.",
            options: [
              "18508, 33240, 47205, 52010, 61088",
              "61088, 52010, 47205, 33240, 18508",
              "18508, 47205, 33240, 52010, 61088",
              "33240, 18508, 47205, 52010, 61088",
            ],
            correctAnswer: "18508, 33240, 47205, 52010, 61088",
            hintLevel1: "දසදහස්ස්ථාන බලන්න: 1, 3, 6, 4, 5.",
            hintLevel2: "කුඩාම සිට විශාලමට දසදහස්ස්ථාන පෙළගස්වන්න: 1 ➔ 3 ➔ 4 ➔ 5 ➔ 6.",
            workedSolution: "දසදහස්ස්ථාන අනුව ආරෝහණ පිළිවෙළ: 18,508 ➔ 33,240 ➔ 47,205 ➔ 52,010 ➔ 61,088.",
            skillTag: "mountain_master_5digit",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },

      // ─── CONCEPT 5: CHALLENGE TRAIN — Mastery challenges ───
      {
        id: "c5_challenge_train",
        conceptId: "c5_challenge_train",
        title: "සංකල්පය 5: පස්වන නැවතුම – අභියෝග දුම්රිය",
        subtitle: "සංඛ්‍යා අභියෝග ජයගමු",
        learningObjective: "ස්ථානීය අගය සහ සංඛ්‍යා සංසන්දන නීති භාවිතයෙන් අභියෝග විසඳීම",
        orderIndex: 5,
        questions: [
          {
            id: "c5_ch1",
            conceptId: "c5_challenge_train",
            interactionType: "multipleChoice",
            questionText: "විශාලම සංඛ්‍යාව ඇති දුම්රිය තෝරන්න.",
            options: ["12450", "21450", "19999"],
            correctAnswer: "21450",
            hintLevel1: "මුලින්ම දසදහස්ස්ථානය බලන්න: 1, 2, 1.",
            hintLevel2: "2 > 1 නිසා 21,450 විශාලයි.",
            workedSolution: "දසදහස්ස්ථානයෙන් 2 > 1 බැවින් 21,450 විශාලම සංඛ්‍යාව වේ.",
            skillTag: "signal_largest_number",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c5_ch2",
            conceptId: "c5_challenge_train",
            interactionType: "multipleChoice",
            questionText: "කුඩාම සංඛ්‍යාව දුම්රිය නැවතුම් ස්ථානයට ඇදගෙන යන්න.",
            options: ["9876", "10205", "8999", "10025"],
            correctAnswer: "8999",
            hintLevel1: "මුලින් සංඛ්‍යාවල ඉලක්කම් ගණන බලන්න.",
            hintLevel2: "ඉලක්කම් 4ක් ඇති සංඛ්‍යා 5ක් ඇති සංඛ්‍යාවලට වඩා කුඩා විය හැක. 8,999 < 10,025.",
            workedSolution: "8,999 ඉලක්කම් 4ක සංඛ්‍යාවක් වන අතර අනෙක්වා ඉලක්කම් 5ක සංඛ්‍යා වේ. එනිසා 8,999 කුඩාම වේ.",
            skillTag: "digit_count_comparison",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c5_ch3",
            conceptId: "c5_challenge_train",
            interactionType: "multipleChoice",
            questionText: "මෙම සංඛ්‍යා තුන කුඩාම සිට විශාලම දක්වා (ආරෝහණ පිළිවෙළට) සකස් කරන්න.",
            options: ["52340, 52403, 52430", "52430, 52403, 52340", "52340, 52430, 52403"],
            correctAnswer: "52340, 52403, 52430",
            hintLevel1: "පළමු ඉලක්කම් දෙක සමානයි (52). ඊළඟ ස්ථානය (සියයස්ථානය) බලන්න.",
            hintLevel2: "52,403 සහ 52,430 දෙකේ සියයස්ථානය 4යි. දැන් දහයස්ථානය බලන්න: 0 < 3.",
            workedSolution: "සියයස්ථානයෙන් 3 < 4 බැවින් 52,340 කුඩාම වේ. 52,403 සහ 52,430 හි දහයස්ථානයෙන් 0 < 3 වේ.",
            skillTag: "deep_place_value_ordering",
            difficulty: 3,
            xpReward: 20,
          },
          {
            id: "c5_ch4",
            conceptId: "c5_challenge_train",
            interactionType: "multipleChoice",
            questionText: "හෝඩුවාවලට (6 දසදහස්, 2 දහස්, 5 සිය) ගැළපෙන සංඛ්‍යාව සොයා තෝරන්න.",
            options: ["62507", "62057", "65207", "52607"],
            correctAnswer: "62507",
            hintLevel1: "දසදහස්ස්ථානයේ 6 සහ දහස්ස්ථානයේ 2 ඇති සංඛ්‍යාව සොයන්න.",
            hintLevel2: "62,507 හි 6 | 2 | 5 | 0 | 7 ලෙස ඉලක්කම් පිහිටා ඇත.",
            workedSolution: "62,507 හි දසදහස් 6, දහස් 2, සිය 5, දහය 0 සහ ඒක 7 පිහිටා ඇත.",
            skillTag: "detective_place_value",
            difficulty: 2,
            xpReward: 15,
          },
          {
            id: "c5_ch5",
            conceptId: "c5_challenge_train",
            interactionType: "multipleChoice",
            questionText: "දුම්රිය ආපසු ගමන් කරයි. සංඛ්‍යා විශාලම සිට කුඩාම දක්වා (අවරෝහණ පිළිවෙළට) සකස් කරන්න.",
            options: ["54201, 52410, 45210, 40512", "40512, 45210, 52410, 54201", "54201, 45210, 52410, 40512"],
            correctAnswer: "54201, 52410, 45210, 40512",
            hintLevel1: "අවරෝහණ පිළිවෙළ කියන්නේ විශාලම සිට කුඩාම දක්වායි.",
            hintLevel2: "දසදහස්ස්ථානයේ 5 ඇති සංඛ්‍යා (54,201 සහ 52,410) පළමුව සසඳන්න.",
            workedSolution: "දසදහස්ස්ථානයෙන් 5 > 4 වේ. 54,201 > 52,410 > 45,210 > 40,512.",
            skillTag: "reverse_carriage_sorting",
            difficulty: 3,
            xpReward: 20,
          },
          {
            id: "c5_ch6",
            conceptId: "c5_challenge_train",
            interactionType: "multipleChoice",
            questionText: "මෙම සංඛ්‍යා 5 කුඩාම සිට විශාලම දක්වා (ආරෝහණ පිළිවෙළට) සකස් කරන්න.",
            options: [
              "25740, 27450, 27540, 70245, 72405",
              "72405, 70245, 27540, 27450, 25740",
              "25740, 27540, 27450, 70245, 72405",
              "27450, 25740, 27540, 70245, 72405",
            ],
            correctAnswer: "25740, 27450, 27540, 70245, 72405",
            hintLevel1: "කුඩාම දසදහස්ස්ථානය 2 ඇති සංඛ්‍යා (25,740, 27,450, 27,540) මුලින්ම සසඳන්න.",
            hintLevel2: "25,740 < 27,450 < 27,540 < 70,245 < 72,405.",
            workedSolution: "අනුපිළිවෙළ: 25,740 ➔ 27,450 ➔ 27,540 ➔ 70,245 ➔ 72,405.",
            skillTag: "challenge_mastery_5digit",
            difficulty: 3,
            xpReward: 20,
          },
        ],
      },
    ],
  },
];
